#!/bin/sh
#
# UCS@school LUSD import
#  postinst script for the debian package
#
# SPDX-FileCopyrightText: 2024-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

#if [ "$1" = "configure" ] && [ -z "$2" ]; then
if [ "$1" = "configure" ]; then
    ucr set \
        cron/LUSD_import/command?/usr/share/ucs-school-import-lusd/scripts/lusd_import \
        cron/LUSD_import/time?"$(shuf -i 0-59 -n 1) $(shuf -i 6-21 -n 1) * * *" \
        cron/LUSD_import/description?"Download and import LUSD user data"
fi
