#!/bin/bash

eval `univention-config-registry shell`

get_schueler(){
	ou=$1
	gidNumber=`ldapsearch -x -b cn="Domain Users $ou,cn=groups,ou=$ou,$ldap_base" gidNumber |grep ^gidNumber| sed -e 's|gidNumber: ||'`
	ldapsearch -x -b cn=schueler,cn=users,ou=$ou,$ldap_base '(&(!(gidNumber='$gidNumber'))(objectclass=posixAccount))' uid | grep "^dn: uid" | sed -e 's|dn: ||'
}

get_lehrer(){
	ou=$1
	gidNumber=`ldapsearch -x -b cn="Domain Users $ou,cn=groups,ou=$ou,$ldap_base" gidNumber | grep ^gidNumber|sed -e 's|gidNumber: ||'`
	ldapsearch -x -b cn=lehrer,cn=users,ou=$ou,$ldap_base '(&(!(gidNumber='$gidNumber'))(objectclass=posixAccount))' uid | grep "^dn: uid" | sed -e 's|dn: ||'
}

set_group(){
	ou=$1
	dn="$2"
	univention-directory-manager users/user modify --dn "$dn" --set primaryGroup="cn=Domain Users $ou,cn=groups,ou=$ou,$ldap_base"
}


ous=`ldapsearch -x ou=* ou -LLL | grep ^ou | sed -e 's|ou: ||'`

for ou in $ous;
  do
  echo "set groups for ou $ou"
  get_lehrer $ou | while read dn; do set_group $ou "$dn"; done
  get_schueler $ou | while read dn; do set_group $ou "$dn"; done
done