#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
# UCS@school lib
#  module: Create role specific shares
#
# SPDX-FileCopyrightText: 2014-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

import sys

from six.moves import input

import univention.admin.modules as udm_modules
import univention.config_registry
from ucsschool.lib.roleshares import create_roleshares
from ucsschool.lib.school_umc_ldap_connection import MACHINE_READ, LDAP_Connection, set_credentials

udm_modules.update()


@LDAP_Connection(MACHINE_READ)
def dn_from_username(username, ucr=None, ldap_machine_read=None, ldap_position=None):
    if not ucr:
        ucr = univention.config_registry.ConfigRegistry()
        ucr.load()

    ldap_filter = "(username=%s)" % (username,)
    try:
        udm_obj = udm_modules.lookup(
            "users/user",
            None,
            ldap_machine_read,
            scope="sub",
            base=ucr.get("ldap/base"),
            filter=str(ldap_filter),
        )[0]
    except IndexError:
        return None
    else:
        return udm_obj.dn


if __name__ == "__main__":
    from argparse import ArgumentParser

    parser = ArgumentParser()
    parser.add_argument(
        "--create", required=True, dest="roleshares", action="append", help="create role share"
    )
    parser.add_argument("--school", dest="schools", action="append", help="select school")
    parser.add_argument("--binddn", help="udm binddn")
    parser.add_argument("--bindpwd", help="udm bindpwd")
    parser.add_argument("--bindpwdfile", help="udm bindpwdfile")
    opts = parser.parse_args()

    ucr = univention.config_registry.ConfigRegistry()
    ucr.load()

    if opts.binddn and opts.bindpwd:
        binddn = opts.binddn
        password = opts.bindpwd
    elif opts.binddn and opts.bindpwdfile:
        binddn = opts.binddn
        with open(opts.bindpwdfile) as fp:
            password = fp.read()
    elif ucr["server/role"] in ("domaincontroller_master", "domaincontroller_backup"):
        try:
            with open("/etc/ldap.secret") as fp:
                password = fp.read()
            binddn = "cn=admin,{}".format(ucr["ldap/base"])
            print("Using cn=admin account")
        except IOError as exc:
            print("Cannot read /etc/ldap.secret: {}".format(exc))
            sys.exit(1)
    else:
        username = input("Administrator name: ")
        if opts.bindpwd:
            password = opts.bindpwd
        else:
            password = input("Password: ")

        binddn = dn_from_username(username, ucr)
        if not binddn:
            print("User not found")
            sys.exit(1)

    set_credentials(binddn, password)  # for @LDAP_Connection(USER_*)

    create_roleshares(opts.roleshares, opts.schools, ucr)
