#!/bin/sh
#
# UCS@school UMC computer room module
#  postinst script
#
# SPDX-FileCopyrightText: 2019-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

if [ "$1" = configure ] && dpkg --compare-versions "$2" lt 11.0.0-12 ; then
	# only set UCR variables during initial package installation and during update from version 11.0.0-12 or earlier
	ucr set \
		"ucsschool/umc/computerroom/wakeonlan/blacklisted/interfaces?lo" \
		"ucsschool/umc/computerroom/wakeonlan/blacklisted/interface_prefixes?tun docker"
fi

systemctl reload univention-management-console-server

exit 0
