#!/bin/sh
#
# Univention UCS@School
#  postinst script
#
# Copyright (C) 2007-2009 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# Binary versions of this file provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

#DEBHELPER#

eval $(ucr shell)

univention-config-registry set ucsschool/userlogon/commonshares?"Marktplatz" \
						ucsschool/userlogon/commonshares/server/Marktplatz?"$hostname" \
						ucsschool/userlogon/commonshares/letter/Marktplatz?"M" \
						ucsschool/userlogon/classshareletter?"K"

mkdir -p /var/lib/samba/userlogon/user
chown listener /var/lib/samba/userlogon/user

# restart listern only listener was running before
/etc/init.d/univention-directory-listener crestart


exit 0
