#!/bin/sh
#
# Univention UCS@school
#  preinst script
#
# SPDX-FileCopyrightText: 2012-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

# save netlogon/user dir and cp old userlogon scripts
# https://forge.univention.org/bugzilla/show_bug.cgi?id=27134
if [ "$1" = "upgrade" -a -n "$2" ] && dpkg --compare-versions "$2" lt 7.0.5; then
	if [ -d /var/lib/samba/netlogon/user ]; then
		mv /var/lib/samba/netlogon/user /var/lib/samba/netlogon/user.$(date +%s)
	fi
	if [ -d /var/lib/samba/userlogon/user ]; then
		cp -rf /var/lib/samba/userlogon/user /var/lib/samba/netlogon/
	fi
fi

exit 0
