#!/bin/sh
#
# Univention UCS@school
#  postrm script
#
# SPDX-FileCopyrightText: 2007-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

if [ -z "$2" ]; then

	# samba 3
	if [ -d "/var/lib/samba/userlogon/user" ]; then
		rm -rf /var/lib/samba/userlogon/user
	fi

	# samba 4
	myrealm=$(echo $kerberos_realm |  awk '{print tolower($0)}')
	if [ -n "$myrealm" ]; then
		if [ -d "/var/lib/samba/sysvol/$myrealm/scripts/user" ]; then
			rm -rf "/var/lib/samba/sysvol/$myrealm/scripts/user"
		fi
	fi
fi

exit 0
