# SPDX-FileCopyrightText: 2025-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "webide"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_OPEN_MERGE_REQUESTS
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_PROTECTED == "true"
    - if: $CI_COMMIT_TAG
    - if: $RUN_UPDATE_RELEASE_ISSUE == "yes"

stages:
  - prepare
  - build
  - test
  - release
  - cleanup

variables:
  RUN_DOCS:
    value: "yes"
    options:
      - "yes"
      - "no"
    description: "Run docs pipeline"
  FORCE_DOCS:
    value: "no"
    options:
      - "yes"
      - "no"
    description: "Force docs pipeline"
  RUN_UPDATE_RELEASE_ISSUE:
    value: "no"
    options:
      - "yes"
      - "no"

include:
  - local: .gitlab-ci/gitlab-ci.yml
    rules:
      - if: $RUN_UPDATE_RELEASE_ISSUE != "yes"
  - local: .gitlab-ci/release.yml
    rules:
      - if: $RUN_UPDATE_RELEASE_ISSUE != "yes"
  - component: $CI_SERVER_FQDN/univention/dev/tooling/ci-components/sonarqube@2.12.0
    inputs:
      job_name: "build-sonar"
      stage: build
    rules:
      - if: $RUN_UPDATE_RELEASE_ISSUE != "yes"
  - local: .gitlab-ci/update_release_issue.yml
    rules:
      - if: $RUN_UPDATE_RELEASE_ISSUE == "yes"
