# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "^django-pam/"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: trailing-whitespace
  - repo: https://git.knut.univention.de/univention/dist/pre-commit-ucr
    rev: '0.0.9'
    hooks:
      - id: ucr-flake8
        additional_dependencies: ["flake8==5.0.4"]
      - id: ucr-ruff
        additional_dependencies: ["ruff==0.0.252"]
      - id: ucr-autopep8
        additional_dependencies: ["autopep8<=2.0.2"]
        stages: [ manual ]
      - id: ucr-ruff-fix
        additional_dependencies: ["ruff==0.0.252"]
        stages: [ manual ]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.252'
    hooks:
      - id: ruff
      - id: ruff
        alias: "ruff-edit"
        stages: [ manual ]
        args: ["--fix"]
  - repo: https://github.com/psf/black
    # Until all Python 3 incompatible code has been removed (-> u"") we have to stay at 21.9b0.
    # Version 21.11b0 adds super annoying Python 2 deprecation notice.
    # Version 22.1.0 removes Python 2 support.
    rev: 21.9b0
    hooks:
      - id: black
        additional_dependencies: ['click>8.0,<8.1']
        entry: black --check --diff --config .black
      - id: black
        additional_dependencies: ['click>8.0,<8.1']
        alias: black-edit
        stages: [ manual ]
        entry: black --config .black
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      # pygrep does not install an environment, so cannot use a language version.
      - id: python-check-blanket-noqa
      - id: python-no-eval
      - id: rst-backticks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        entry: bandit -c .bandit --exclude ucs-test-ucsschool
default_language_version:
    python: python3.7
