# SPDX-FileCopyrightText: 2025-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

version = 1
SPDX-PackageName = "UCS@school"
SPDX-PackageSupplier = "Univention GmbH <info@univention.de>"
SPDX-PackageDownloadLocation = "https://www.univention.com/products/ucsschool/"

# MAKE SURE THIS IS IN SYNC WITH: .pre-commit-config.yaml: reuse-annotate
[[annotations]]
path = [
    "**.gitignore",
    ".bandit",
    ".black",
    ".flake8",
    ".git-blame-ignore-revs",
    ".gitlab-ci/branch_tests.cfg",
    ".gitlab-ci/build-ci",
    ".gitlab-ci/changelog-checks",
    ".gitlab-ci/check-bugzilla-bugs",
    ".gitlab-ci/find-advisories",
    ".gitlab-ci/rename-advisories",
    ".gitlab-ci/validate-advisories",
    ".gitlab/issue_templates/*.md",
    ".gitlab/merge_request_templates/*.md",
    "CODE_OF_CONDUCT.md",
    "CONTRIBUTING.md",
    "PULL_REQUEST_TEMPLATE.md",
    "SECURITY.md",
    "appcenter/README_DE",
    "appcenter/README_EN",
    "appcenter/README_UPDATE_DE",
    "appcenter/README_UPDATE_EN",
    "appcenter/settings",
    "doc/*/spelling_wordlist",
    "doc/devel/architecture-graphs/Role_and_Access_Model/ram_sequence.txt",
    "doc/devel/ram/**/*.rego",
    "doc/devel/ram/guardian_api/requirements",
    "doc/errata/**.yaml",
    "doc/errata/erratum.schema.json",
    "doc/pipeline-rsync-exclude.txt",
    "doc/substitutions-de.txt",
    "doc/substitutions-en.txt",
    "pyproject.toml",
    "release-postup-preup/README.txt",
    "test/**.cfg",
    "ucs-test-ucsschool/90_ucsschool/factoryconftest.json",
    "basedpyright-baseline.json",
]
SPDX-FileCopyrightText = "2025-2026 Univention GmbH"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = [
    "doc/**.csv",
    "doc/**.drawio",
    "doc/**.jpeg",
    "doc/**.jpg",
    "doc/**.json",
    "doc/**.pdf",
    "doc/**.png",
    "doc/**.svg",
    # FIXME: all of the following should be part of the debian/copyright instead
    "**/umc/icons/**.png",
    "**/umc/icons/**.svg",
    "**/umc/icons/**.svgz",
    "ucs-school-import-lusd/usr/share/ucs-school-import-lusd/**.json",
    "ucs-school-import/examples/*.csv",
    "ucs-school-import/usr/share/doc/**",
    "ucs-school-import/usr/share/ucs-school-import/configs/*.json",
    "ucs-school-import/usr/share/ucs-school-import/schema/*.json",
    "ucs-school-metapackage/ucsschool.png",
    "ucs-school-metapackage/ucsschool.svg",
    "ucs-school-netlogon-user-logonscripts/*.png",
    "ucs-school-umc-common/data/icons/scalable/category-ucs-school-*.svg",
    "ucs-school-umc-lists/umc/js/schoollists/lo_import_hl_*.png",
]
SPDX-FileCopyrightText = "2025-2026 Univention GmbH"
SPDX-License-Identifier = "LicenseRef-Univention-Proprietary"

## BEGIN AUTOMATIC GENERATED COPYRIGHT INFORMATION
# This block is auto-generated by update-reuse-toml.py. Do not edit manually.

[[annotations]]
path = "django-pam/**"
precedence = "override"
SPDX-License-Identifier = "MIT"
SPDX-FileCopyrightText = "2016 Carl J. Nobile"

[[annotations]]
path = "django-pam/debian/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2012-2025 Univention GmbH"

[[annotations]]
path = "ucs-school-branding/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2012-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-import/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2016-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-import/modules/ucsschool/importer/contrib/csv.py"
precedence = "override"
SPDX-License-Identifier = "Python-2.0"
SPDX-FileCopyrightText = "2001-2006 Python Software Foundation; All Rights Reserved"

[[annotations]]
path = "ucs-school-import-lusd/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2009-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-info/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2010-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-l10n-fr/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2016-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-ldap-acls-master/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2004-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-lib/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2012-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-metapackage/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2009-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-netlogon/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2002-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-netlogon-user-logonscripts/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2007-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-old-homedirs/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2007-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-old-sharedirs/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2007-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-ox-support/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2017-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-radius-802.1x/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2011-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-roleshares/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2014-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-selfservice-support/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2017-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-umc-common/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2012-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-umc-computerroom/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2012-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-umc-diagnostic/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2014-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-umc-distribution/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2012-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-umc-exam/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2013-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-umc-groups/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2012-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-umc-helpdesk/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2007-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-umc-import/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2017-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-umc-installer/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2013-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-umc-internetrules/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2012-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-umc-lessontimes/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2012-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-umc-lists/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2018-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-umc-printermoderation/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2012-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-umc-rooms/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2012-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-umc-users/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2012-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-umc-wizards/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2012-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-veyon-client/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2018-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-veyon-windows/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2021-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-webproxy/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2007-2026 Univention GmbH"

[[annotations]]
path = "ucs-test-ucsschool/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2014-2026 Univention GmbH"

[[annotations]]
path = "univention-management-console-module-selective-udm/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2012-2026 Univention GmbH"

## END AUTOMATIC GENERATED COPYRIGHT INFORMATION
