sonar.projectKey=univention_ucsschool_5adf8727-ef52-4a18-b927-519fbf2e5da3
sonar.qualitygate.wait=true
sonar.python.version=3.11
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=ucs-test-ucsschool/**/*,**/unittests/**/*
sonar.exclusions=django-pam/**/*
