# SPDX-FileCopyrightText: 2025-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

sonar.projectKey=univention_dev_education_ucsschool_fc82873d-5211-4bc7-b776-d205ac36a6df
sonar.qualitygate.wait=true
sonar.python.version=3.11
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=ucs-test-ucsschool/**/*,**/unittests/**/*
sonar.exclusions=django-pam/**/*
