#!/bin/sh
#
# UCS@school Python
#  postinst file for the debian package
#
# SPDX-FileCopyrightText: 2012-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

if [ ! -e /var/lib/ucs-school-lib/lessons.ini ]; then
	cp /usr/share/ucs-school-lib/lessons.ini /var/lib/ucs-school-lib/
fi

ucr set ucsschool/default/share/nfs?false

# update default layer (Bug #57958)
ucr update

exit 0
