# SPDX-FileCopyrightText: 2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

include:
  - project: 'univention/dev/docs/sphinx-docker'
    file: 'pipeline/sphinx.yml'

stages:
  - build
  - merge
  - production

.sphinx-doc:
  stage: build
  image: $SPHINX_BASE
  variables:
    DOC_TARGET_VERSION: "5.2"
    CHANGELOG_TARGET_VERSION: $APP_VERSION
    language: "de"
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: create_app_version
      artifacts: true

.sphinx-html:
  extends:
    - .sphinx-html-template
    - .sphinx-doc

.sphinx-pdf:
  extends:
    - .sphinx-doc
    - .sphinx-pdf-template

.sphinx-linkcheck:
  extends:
    - .sphinx-doc
    - .sphinx-linkcheck-template

.sphinx-spelling:
  extends:
    - .sphinx-doc
    - .sphinx-spelling-template
