#!/bin/sh
# shellcheck disable=SC2016
set -e -u

exec >generated-config-doc.yml
cat "${0%/*}/base.yml"
cat "${0%/*}/base-doc.yml"

doc_job () { # <extends> [<suffix> [<language>]]
	echo
	echo "build ${pkg}${3:+ "$3"}${2:+ "$2"}:"
	echo '  variables:'
	echo "    base: $path"
	echo "    DOC_NAME: ${path##*/}"
	[ -n "${3+empty}" ] && echo "    language: $3"

    if [ "$pkg" = "ucsschool-changelog" ] && ( [ "$2" = "html" ] || [ "$2" = "pdf" ] )
    then
        echo '    DOC_TARGET_VERSION: $CHANGELOG_TARGET_VERSION'
    fi
	echo "  extends: ${1:?extends}"
	echo '  rules:'
	echo '    - changes:'
	echo "      - ${path}/**/*"
	echo '      - doc/bibliography-de.bib'
	echo '      - doc/substitutions-de.txt'
	echo '    - if: "$pipeline =~' "/force-doc-${pkg}/\""
}

prod_job () {
    echo
    echo "production ${pkg}:"
    echo '  variables:'
    echo "    DOC_NAME: ${path##*/}"
    echo '  extends: .production'

    echo "  needs: "
    for l_path in "$path"/locales/* "$lang_default"
    do
        language="${l_path##*/}"
        [ "$language" = '*' ] && continue
        echo "    - job: build ${pkg} ${language} html"
        echo "    - job: build ${pkg} ${language} pdf"
        echo "    - job: build ${pkg} ${language} spelling"
        echo "      artifacts: false"
        echo "    - job: build ${pkg} ${language} linkcheck"
        echo "      artifacts: false"
    done
    echo '  rules:'
    echo '    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"'
    echo '      changes:'
    echo "      - ${path}/**/*"
    echo '      - doc/bibliography-de.bib'
    echo '      - doc/substitutions-de.txt'
    echo '      when: manual'
    echo '    - if: "$pipeline =~' "/force-doc-${pkg}/\""
}

for make in doc/*/Makefile
do
	[ -f "$make" ] || continue
	path="${make%/Makefile}"
	pkg="${path##*/}"

	# Automatically detect Sphinx or Docbook
	if [ -f "${path}/conf.py" ] # Use Sphinx's conf.py as hint to Sphinx
	then
	    if [ "$pkg" = "ucsschool-changelog" ]
		then
			lang_default="en"
		else
			lang_default="de"
		fi

		for l_path in "$path"/locales/* "$lang_default"
		do
			language="${l_path##*/}"
			[ "$language" = '*' ] && continue
			doc_job '.sphinx-html' html "$language"
			doc_job '.sphinx-pdf' pdf "$language"
			doc_job '.sphinx-linkcheck' linkcheck "$language"
			doc_job '.sphinx-spelling' spelling "$language"
		done
        prod_job
	fi
done
