#!/bin/sh
# shellcheck disable=SC2016
set -e -u

exec >generated-config-doc.yml
cat "${0%/*}/base.yml"
cat "${0%/*}/base-doc.yml"

doc_job () { # <extends> [<suffix> [<language>]]
	echo
	echo "build ${pkg}${3:+ "$3"}${2:+ "$2"}:"
	echo '  variables:'
	echo "    base: $path"
	echo "    DOC_NAME: ${path##*/}"
	[ -n "${3+empty}" ] && echo "    language: $3"
	echo "  extends: ${1:?extends}"
	echo '  rules:'
	echo '    - changes:'
	echo "      - ${path}/**/*"
	echo '      - doc/bibliography-de.bib'
	echo '      - doc/substitutions-de.txt'
}

prod_job () {
    echo
    echo "production ${pkg}:"
    echo '  variables:'
    echo "    DOC_NAME: ${path##*/}"
    echo '  extends: .production'
    echo "  needs: [\"build ${pkg} de html\", \"build ${pkg} de pdf\"]"
    echo '  rules:'
    echo '    - if: \'$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH\''
    echo '      when: manual'
    echo '    - changes:'
    echo "      - ${path}/**/*"
}

for make in doc/*/Makefile
do
	[ -f "$make" ] || continue
	path="${make%/Makefile}"
	pkg="${path##*/}"

	# Automatically detect Sphinx or Docbook
	if [ -f "${path}/conf.py" ] # Use Sphinx's conf.py as hint to Sphinx
	then
		for l_path in "$path"/locales/* "de"
		do
			language="${l_path##*/}"
			[ "$language" = '*' ] && continue
			doc_job '.sphinx-html' html "$language"
			doc_job '.sphinx-pdf' pdf "$language"
			doc_job '.sphinx-linkcheck' linkcheck "$language"
			doc_job '.sphinx-spelling' spelling "$language"
		done
        prod_job
	fi
done
