# SPDX-FileCopyrightText: 2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

generate-config:
  stage: prepare
  image:
    name: docker-registry.knut.univention.de/knut/deb-builder
    entrypoint: [""]
  script:
    - .gitlab-ci/build-ci
  artifacts:
    paths:
      - generated-config-doc.yml

doc-pipeline:
  stage: build
  variables:
    PARENT_CI_PIPELINE_SOURCE: $CI_PIPELINE_SOURCE
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  needs:
    - job: generate-config
    - job: create_app_version
  trigger:
    include:
      - artifact: generated-config-doc.yml
        job: generate-config
    strategy: depend
    forward:
      pipeline_variables: true
