# SPDX-FileCopyrightText: 2025-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

include:
  - component: $CI_SERVER_FQDN/univention/dev/tooling/ci-components/app-release@main
    inputs:
      app_id: "ucsschool"
      mail_sender: "ucsschool-team@univention.de"
      author_alias: "UCS@school Team"
      mail_subject: "UCS@school package update"
      changelog_link: "https://docs.software-univention.de/ucsschool-changelog/latest/en/index.html"
      mail_recipient: "app-announcement@univention.de"
      chat_destination: "#ucsschool"
      ucs_base_version: "5.2"
      release_tag_constraint: '\d.\d+v\d+'
      app_staging_version: "999.0.0-staging"
  - component: $CI_SERVER_FQDN/univention/dev/tooling/ci-components/debian-package@main
    inputs:
      ucs_base_version: "5.2"
      scope: "ucs-school-5.2"
      additional_upload_needs:
        - parse-advisories
        - create_app_version

parse-advisories:
  stage: build
  image: gitregistry.knut.univention.de/univention/dev/tooling/ci-components/python:latest
  script:
    - .gitlab-ci/extract-info-from-advisory.py
  artifacts:
    reports:
      dotenv: .dotenv
    paths:
      - doc/errata/staging/ucs-test-ucsschool.yaml

check-tests:
  stage: build
  rules:
    - if: "$CI_COMMIT_TAG"
  script:
    - echo "check tests"
  manual_confirmation: "Are the tests green?"
  when: manual

update-doc-repos:
  stage: build
  rules:
    - if: "$CI_COMMIT_TAG"
  script:
    - echo "update doc repos"
  manual_confirmation: "Did you update the doc repos?"
  when: manual

check-advisory-files-end-in-yaml:
  stage: build
  script:
    - non_yaml_files=( $(find doc/errata/staging -type f -not -name "*.yaml") )
    - |-
      if [ -z "$non_yaml_files" ]; then
        echo "All files correctly named with '.yaml' extension"
        exit 0
      else
        echo "Files found without a .yaml extension. Please correct this error:"
        for filename in "${non_yaml_files[@]}"; do
          echo $filename
        done
        exit 1
      fi

check-bugzilla-bugs:
  stage: build
  rules:
    - if: "$CI_COMMIT_TAG"
  before_script:
    - apt update && apt install -y curl jq
  script:
    - .gitlab-ci/check-bugzilla-bugs "$RELEASE_BUGS"
  needs: [parse-advisories]

deb_repo_import:
  needs: [parse-advisories]

deb_build_git:
  needs: [parse-advisories]

validate-advisories:
  stage: build
  rules:
    - if: "$CI_COMMIT_TAG"
  before_script:
    - apt update && apt install -y python3 python3-pip
    - pip3 install packaging pyyaml --break-system-packages
  script:
    - advisories=$(find doc/errata/staging/ -name "*.yaml" -not -name "0template.yaml")
    - ./.gitlab-ci/validate-advisories $advisories

rename-advisories:
  stage: cleanup
  variables:
    GIT_AUTHOR_EMAIL: "ucsschool-team@univention.de"
    GIT_AUTHOR_NAME: "UCS@school team"
  rules:
    - if: "$CI_COMMIT_TAG"
  image: gitregistry.knut.univention.de/univention/dev/tooling/ci-components/python:latest
  script:
    - .gitlab-ci/rename-advisories

close-bugzilla:
  stage: cleanup
  when: manual
  rules:
    - if: "$CI_COMMIT_TAG"
  manual_confirmation: "Did you close all released bugzilla bugs?"
  script:
    - echo "close bugs in bugzilla"
