#!/usr/bin/env bash

set -e
git config user.name "${GIT_AUTHOR_NAME:?}"
git config user.email "${GIT_AUTHOR_EMAIL:?}"
git remote set-url --push origin "$CI_SERVER_PROTOCOL://pipeline_token:$GITLAB_PROJECT_TOKEN@$CI_SERVER_FQDN/$CI_PROJECT_PATH_SLUG"
git switch -c releasebot/release
release_files=$(find doc/errata/staging/ -name "*.yaml" -not -name "0template.yaml")
cd doc/errata/staging
# move advisories from staging to published
for file in "${release_files[@]}"; do git mv "$file" "$(echo "$file" | sed "s/^/..\/published\/$(date +%Y-%m-%d)-/")"; done
cd "$CI_PROJECT_PATH"
git add doc/errata
git commit -m "chore: move yaml advisories to published" -m "Issue univention/ucsschool#1406"
# TODO: merge_when_pipeline_succeeds is deprecated with 17.11, but we are still on gitlab 17.10, replace with auto_merge
git push -u \
    -o merge_request.remove_source_branch \
    -o merge_request.title="Automatic Merge: UCS@school Release - Move of yaml advisories" \
    -o merge_request.merge_when_pipeline_succeeds \
    -o merge_request.create \
    -o merge_request.target="$APP_UCS_VERSION" \
    -o merge_request.assign="$GITLAB_USER_LOGIN" origin "$(git branch --show-current)"
