# SPDX-FileCopyrightText: 2025-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

update release issue:
  stage: build
  image: gitregistry.knut.univention.de/univention/dev/tooling/ci-components/python:latest
  script:
    - .gitlab-ci/update_release_issue.py
