stages:
  - build

update release issue:
  stage: build
  image: gitregistry.knut.univention.de/univention/dev/internal/ucsschool-ci-utils/python:latest
  script:
    - .gitlab-ci/update_release_issue.py
