#!/usr/bin/env python3

# ########################################################################### #
#                                                                             #
#  Check that the expected fields are present in all advisories and the       #
#  format of the fields is correct.                                           #
#                                                                             #
#  This script takes a list of paths to the advisories to be validated:       #
#                                                                             #
#      validate-advisories doc/errata/staging/advisory-1.yaml ...             #
#                                                                             #
# ########################################################################### #

import os
import re
import sys
from typing import List

import yaml


def get_latest_package(package_name: str) -> str:
    filename = f"{package_name}/debian/changelog"
    package_version = "Unknown"
    try:
        with open(filename) as changelog_file:
            changelog = changelog_file.readlines()
            for line in changelog:
                if package_name == "ucs-school-veyon-windows":
                    version = re.match(
                        f"{package_name} \\((\\d+\\.\\d+\\.\\d+.\\d+-ucs\\d+\\.\\d+-\\d+)\\)", line
                    )
                else:
                    version = re.match(f"{package_name} \\((\\d+\\.\\d+\\.\\d+)\\)", line)
                if version:
                    package_version = version.groups()[0]
                    break

    except FileNotFoundError:
        print(f"ERROR: changelog missing for {package_name}")

    return package_version


def get_changelog() -> str:
    filename = "doc/ucsschool-changelog/changelog.rst"
    try:
        with open(filename) as changelog_file:
            return changelog_file.read()
    except FileNotFoundError:
        print("ERROR: changelog.rst missing.")
    return ""


def check_yaml_content(filename: str) -> List[str]:
    """
    :param filename: path to the advisory file
    :return: list of strings: errors found while validating yaml
    """
    errors = []

    with open(filename) as advisory_file:
        advisory = yaml.safe_load(advisory_file)
        if not advisory:
            errors.append(f"could not load {filename}, invalid yaml")
            return errors

    product = advisory.get("product")
    if product is None:
        errors.append("product is missing")
    elif product != "ucsschool":
        errors.append("product must be 'ucsschool'")

    release = advisory.get("release")
    if release is None:
        errors.append("release is missing")
    elif not isinstance(release, str):
        errors.append("release should be a string, not a number")
    elif not re.match(r"^\d+\.\d+$", release):
        errors.append("release format incorrect -- example: '5.0'")

    version = advisory.get("version")
    if version is None:
        errors.append("version is missing")
    elif version != [0]:
        errors.append("version should be [0]")

    src = advisory.get("src")
    expected_src_package = os.path.splitext(os.path.basename(filename))[0]
    if src is None:
        errors.append("src is missing")
    elif src != expected_src_package:
        errors.append("src or yaml file name is wrong")

    fix = advisory.get("fix")
    expected_fix_version = get_latest_package(expected_src_package)
    if fix is None:
        errors.append("fix is missing")
    elif fix != expected_fix_version:
        errors.append(f"fix version is {fix}, expected {expected_fix_version}")

    raw_bugs = advisory.get("bugs")
    if not raw_bugs:
        errors.append("bugs is missing")
    elif not isinstance(raw_bugs, dict):
        errors.append("bug should be a dictionary")
    else:
        for bug, texts in raw_bugs.items():
            if not (bug == "notes" or isinstance(bug, int)):
                errors.append(f"Bugs must either be a number or 'notes': {bug}")
            if not (isinstance(texts, list) or isinstance(texts, dict)):
                errors.append(f"Values for bug {bug} must be either a list or a dictionary")
            if not isinstance(texts, list):
                texts = [texts]
            for text in texts:
                if not text.get("en", None):
                    errors.append(f"A bug must contain an english text: {bug}")
                if not text.get("de", None):
                    errors.append(f"A bug must contain a german text: {bug}")

    return errors


def check_yaml_files(advisories: List[str]) -> None:
    """
    :param advisories: list of paths to advisory files to check
    :return: None
    """
    errors = {}
    for advisory in advisories:
        advisory_errors = check_yaml_content(advisory)
        if advisory_errors:
            errors[advisory] = advisory_errors

    if errors:
        print("Errors found in advisories!")
        for filename, errs in errors.items():
            print(f"{filename}:")
            for err in errs:
                print(f"\t- {err}")
        sys.exit(1)
    else:
        print("All advisories validated.")


if __name__ == "__main__":
    check_yaml_files(sys.argv[1:])
