#!/bin/sh
#
# -*- coding: utf-8 -*-
#
# Univention UCS@School
#
# Copyright (C) 2007-2010 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# Binary versions of this file provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

OU="$(echo "$1" | tr -cd 'a-zA-Z0-9-')"
USERNAMECACHE_P="$(mktemp /tmp/tmp.ucsschool.p.XXXXXXXXX)"
USERNAMECACHE_T="$(mktemp /tmp/tmp.ucsschool.t.XXXXXXXXX)"
FIRSTNAMES="Anton Bertram Christina Daniela Ernst Friderike Gisela Hans Ines Jens Klaus Lisa Marlene Norbert Otto Pauline Richard Silke Tim Ulrike Victor Wilhelmine"
LASTNAMES="Meyer Schmidt Schulz Müller Schneider Fischer Weber Wagner Becker Koch Richter Lange"
CLASSES="1A 1B 2A 2B 3B 3C 4B 4r Froesche Igel"

trap "rm -Rf ${USERNAMECACHE_P} ${USERNAMECACHE_P}.* ${USERNAMECACHE_T} ${USERNAMECACHE_T}.*" EXIT

if [ -z "$OU" -o "$OU" = "-h" -o "$OU" = "--help" ] ; then
	echo "syntax: $0 <ou>"
	exit 1
fi

rotate_classes() {
	CLASSES="$(echo "$CLASSES" | cut -d' ' -f2-) $(echo "$CLASSES" | cut -d' ' -f1)"
}

get_class() {
	CLASS="$OU-$(echo "$CLASSES" | cut -d' ' -f1)"
}

get_username_pupils() {
	local usernamepart="$1"
	local fn="${USERNAMECACHE_P}.${usernamepart}"
	if [ ! -f "$fn" ] ; then
		let i=1
	else
		let i="$(cat $fn)"
		let i=i+1
	fi
	echo "$i" > "$fn"
	ACCOUNTNAME="${usernamepart}$i"
}

get_username_teacher() {
	local fname="$1"
	local lname="$(echo $2 | tr '[:upper:]' '[:lower:]')"
	local usernamepart="${fname:0:1}.${lname:0:8}"

	local fn="${USERNAMECACHE_T}.${usernamepart}"
	if [ ! -f "$fn" ] ; then
		let i=1
	else
		let i="$(cat $fn)"
		let i=i+1
	fi
	echo "$i" > "$fn"

	ACCOUNTNAME="${usernamepart}$i"
}

eval $(/usr/sbin/ucr shell)

# create pupils
for fn in $FIRSTNAMES ; do
	for ln in $LASTNAMES ; do
		get_username_pupils "$fn"
		get_class
		echo -e "A\t${ACCOUNTNAME}\t$ln\t$fn\t$OU\t$CLASS\t\t${ACCOUNTNAME}@${domainname}\t0\t1\t0"
		rotate_classes
	done
done

# create teachers
for fn in Daniel Gabriele ; do
	for ln in Krause Lehmann ; do
		get_username_teacher "$fn" "$ln"
		classlist="${OU}-$(echo $CLASSES | sed -e "s| |,$OU-|g")"
		echo -e "A\t${ACCOUNTNAME}\t$ln\t$fn\t$OU\t$classlist\t\t${ACCOUNTNAME}@${domainname}\t1\t1\t0"
	done
done
