#!/bin/sh
#
# Univention UCS@School
#
# Copyright 2007-2014 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.
#

. /usr/share/univention-lib/all.sh

OU="$1"
DNOLD="$2"
DNNEW="$3"

if [ -z "$OU" -o -z "$DNOLD" -o -z "$DNNEW" ] ; then
	echo "This tool changes all responsible fileservers of share objects within given"
	echo "OU to a new fileserver if the given old fileserver matches. The same is done"
	echo "with printservers of all matching printer share object within given OU."
	echo "$0 <ou> <olddn> <newdn>"
	echo
	echo "<ou>      name of OU to look for file shares/printer shares"
	echo "<olddn>   DN of old server object"
	echo "<newdn>   DN of new server object"
	exit 1
fi

eval "$(univention-config-registry shell)"

FQDNOLD="$(univention-ldapsearch -LLL -x -b "$DNOLD" uid | grep ^uid | sed -re 's|uid: ||' -e 's|\$$||').$domainname"
FQDNNEW="$(univention-ldapsearch -LLL -x -b "$DNNEW" uid | grep ^uid | sed -re 's|uid: ||' -e 's|\$$||').$domainname"

district=""
if is_ucr_true "ucsschool/ldap/district/enable" ; then
	district=",ou=${OU:0:2}"
fi

echo "OU: $OU"
echo "old server fqdn: $FQDNOLD"
echo "new server fqdn: $FQDNNEW"
echo ""
echo "changing file shares"
univention-ldapsearch -LLL -b "ou=$OU${district},$ldap_base" -x "(&(objectClass=univentionShare)(univentionShareHost=$FQDNOLD))" dn | ldapsearch-wrapper | grep ^dn | sed -re 's|^dn: ||' | while read dn; do
	univention-directory-manager shares/share modify --dn "$dn" --set host="$FQDNNEW"
done

echo ""
echo "changing printer shares"
univention-ldapsearch -LLL -b "ou=$OU${district},$ldap_base" -x "(&(objectClass=univentionPrinter)(univentionPrinterSpoolHost=$FQDNOLD))" dn | ldapsearch-wrapper | grep ^dn | sed -re 's|^dn: ||' | while read dn; do
	univention-directory-manager shares/printer modify --dn "$dn" --set spoolHost="$FQDNNEW"
done
