#!/usr/share/ucs-test/runner bash
## desc: In-container integration tests
## exposure: dangerous
## tags: [id_sync]

CMD="/id-sync/venv/bin/python -m pytest -l -v /id-sync/src/integration_tests"

echo "BB-API Key of Traeger 1: $(/var/www/bb-api-key_traeger1.txt)"
echo "BB-API Key of Traeger 2: $(/var/www/bb-api-key_traeger2.txt)"

echo "Running in container: '$CMD'"

univention-app shell id-sync $CMD
