#!/bin/bash
#
# UCS@school
#
# SPDX-FileCopyrightText: 2009-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

. /usr/share/univention-lib/all.sh

univention-config-registry set \
	directory/manager/samba3/legacy?yes \
	connector/s4/mapping/sid_to_ucs?no \
	connector/s4/mapping/sid_to_s4?yes \
	connector/s4/mapping/group/syncmode?write \
	listener/shares/rename?yes \
	samba4/join/dnsupdate?true \
	samba4/sysvol/sync/setfacl/AU?false \
	samba/script/addmachine?'/usr/share/univention-samba/addmachine.sh "%u"' \
	connector/s4/mapping/wmifilter?yes \
	connector/s4/mapping/msprintconnectionpolicy?yes \
	connector/s4/mapping/msgpwl?yes \
	connector/s4/mapping/gpo/ntsd?yes \
	connector/s4/mapping/group/ignorelist?"Windows Hosts,Authenticated Users,World Authority,Everyone,Null Authority,Nobody,Replicators,Printer-Admins,System Operators,Enterprise Domain Controllers,Remote Interactive Logon,SChannel Authentication,Digest Authentication,Terminal Server User,NTLM Authentication,Other Organization,This Organization,Anonymous Logon,Network Service,Creator Group,Creator Owner,Local Service,Owner Rights,Interactive,Restricted,Network,Service,Dialup,System,Batch,Proxy,IUSR,Self,Console Logon" \
	ucsschool/import/generate/policy/dhcp/dns/set_per_ou?true \
	ucsschool/singlemaster?true \
	ldap/refint=true

if [ "$1" = "configure" -a -n "$2" ]; then
	if dpkg --compare-versions "$2" lt 12.0.2-8 && is_ucr_true nss/group/cachefile/check_member; then
		# Bug #50905: increase performance by not checking group members by default in ldap-group-to-file.py
		univention-config-registry unset nss/group/cachefile/check_member
	fi
fi

if [ "$1" = configure -a -z "$2" ]; then
	# fresh installation
	# prevent sysvol-sync of netlogon scripts
	if [ -z "$(ucr get samba/share/netlogon/path)" -a -z "$(ucr get ucsschool/userlogon/netlogon/path)" ]; then
		univention-config-registry set \
			samba/share/netlogon/path=/var/lib/samba/netlogon \
			ucsschool/userlogon/netlogon/path=/var/lib/samba/netlogon/user
	fi
	univention-config-registry set ucsschool/join/create_demo?yes
fi

# Bug 49515: store demo user password in ucsschool config dir
if [ "$1" = configure ] && dpkg --compare-versions "$2" lt 12.0.2-3; then
	if [ -e /etc/demoschool.secret ]; then
		[ -d /etc/ucsschool ] || mkdir -p /etc/ucsschool
		mv /etc/demoschool.secret /etc/ucsschool
	fi
fi

# Bug 49531: demo_admin missing an OC
if [ "$1" = configure ] && dpkg --compare-versions "$2" lt-nl 12.0.2-4; then
	if univention-ldapsearch -LLL uid=demo_admin dn | grep -q uid=demo_admin && ! univention-ldapsearch -LLL uid=demo_admin objectClass | grep -q ucsschoolAdministrator; then
		udm users/user modify \
			--dn "uid=demo_admin,cn=mitarbeiter,cn=users,ou=DEMOSCHOOL,$(ucr get ldap/base)" \
			--append-option ucsschoolAdministrator
	fi
fi

# Bug 52049: deactivate sync of msgpipsec, msgpsi
if [ "$1" = configure ] && dpkg --compare-versions "$2" lt-nl 12.0.3-7; then
	ucr unset connector/s4/mapping/msgpipsec connector/s4/mapping/msgpsi
	systemctl try-restart univention-s4-connector || true
fi

systemctl try-restart univention-directory-listener

#DEBHELPER#

exit 0
