#!/bin/bash
#
# UCS@school
#
# SPDX-FileCopyrightText: 2009-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

. /usr/share/univention-lib/all.sh

if [ "$1" = configure -a -z "$2" ]; then
	# overwrite the netlogon sync setting during the installation
	univention-config-registry set samba/netlogon/sync=download

	# fresh installation
	# prevent sysvol-sync of netlogon scripts
	if [ -z "$(ucr get samba/share/netlogon/path)" -a -z "$(ucr get ucsschool/userlogon/netlogon/path)" ]; then
		univention-config-registry set \
			samba/share/netlogon/path=/var/lib/samba/netlogon \
			ucsschool/userlogon/netlogon/path=/var/lib/samba/netlogon/user
	fi

	if dpkg --compare-versions "$2" lt 12.0.2-8 && is_ucr_true nss/group/cachefile/check_member; then
		# Bug #50905: increase performance by not checking group members by default in ldap-group-to-file.py
		univention-config-registry unset nss/group/cachefile/check_member
	fi
fi

univention-config-registry set \
	directory/manager/samba3/legacy?yes \
	connector/s4/mapping/sid_to_ucs?no \
	connector/s4/mapping/sid_to_s4?yes \
	connector/s4/mapping/group/syncmode?write \
	connector/s4/allow/secondary?true \
	samba4/service/drepl?false \
	samba4/provision/secondary=yes \
	listener/shares/rename?yes \
	dns/register/srv_records/kerberos?false \
	dns/register/srv_records/ldap?false \
	samba4/join/dnsupdate?true \
	samba4/sysvol/sync/setfacl/AU?false \
	connector/s4/mapping/wmifilter?yes \
	connector/s4/mapping/msprintconnectionpolicy?yes \
	connector/s4/mapping/msgpwl?yes \
	connector/s4/mapping/gpo/ntsd?yes \
	connector/s4/mapping/group/ignorelist?"Windows Hosts,Authenticated Users,World Authority,Everyone,Null Authority,Nobody,Replicators,Printer-Admins,System Operators,Enterprise Domain Controllers,Remote Interactive Logon,SChannel Authentication,Digest Authentication,Terminal Server User,NTLM Authentication,Other Organization,This Organization,Anonymous Logon,Network Service,Creator Group,Creator Owner,Local Service,Owner Rights,Interactive,Restricted,Network,Service,Dialup,System,Batch,Proxy,IUSR,Self,Console Logon" \
	ucsschool/import/generate/policy/dhcp/dns/set_per_ou?true \
	dns/nameserver/registration/forward_zone?no \
	dns/nameserver/registration/reverse_zone?no \
	connector/s4/mapping/ignoresubtree/01_keys?"CN=Keys,$(ucr get ldap/base)"

if [ "$1" = "configure" ] ; then
	if [ -z "$2" ] ; then
		### Defaults for new installations of Replica Directory Node PDCs
		univention-config-registry set samba4/ignore/mixsetup?yes samba3/ignore/mixsetup?yes	## necessary for migration of Samba3 to Samba4
	fi
fi

# Bug 48534: remove dns-$hostname from ignore list
if [ "$1" = configure ] && dpkg --compare-versions "$2" lt-nl 12.0.0-6; then
	old_ignore="$(ucr get connector/s4/mapping/user/ignorelist)"
	new_ignore=''
	dnsname="dns-$(hostname)"
	OIFS="$IFS"
	IFS=$','
	if echo "$old_ignore" | grep -q -w "$dnsname"; then
		for i in $old_ignore; do
			test "$i" = "$dnsname" && continue
			test -n "$new_ignore" && new_ignore+=","
			new_ignore+="$i"
		done
		IFS="$OIFS"
		if [ -n "$new_ignore" ]; then
			test ! "$old_ignore" = "$new_ignore" && ucr set connector/s4/mapping/user/ignorelist="$new_ignore"
		else
			ucr unset connector/s4/mapping/user/ignorelist
		fi
		systemctl try-restart univention-s4-connector || true
	fi
	IFS="$OIFS"
fi

# Bug 52049: deactivate sync of msgpipsec, msgpsi
if [ "$1" = configure ] && dpkg --compare-versions "$2" lt-nl 12.0.3-7; then
	ucr unset connector/s4/mapping/msgpipsec connector/s4/mapping/msgpsi
	systemctl try-restart univention-s4-connector || true
fi

systemctl try-restart univention-directory-listener

call_joinscript 00ucs-school-app-version-check.inst
call_joinscript 00ucs-school-replica-check-ou.inst
#DEBHELPER#
call_joinscript 96univention-samba4slavepdc.inst
call_joinscript 98univention-samba4slavepdc-dns.inst

exit 0
