#!/bin/bash
#
# UCS@school
#
# SPDX-FileCopyrightText: 2019-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

. /usr/share/univention-lib/all.sh

if [ "$1" = configure -a -z "$2" ]; then
	# overwrite the netlogon sync setting during the installation
	univention-config-registry set samba/netlogon/sync=download

	# fresh installation
	# prevent sysvol-sync of netlogon scripts
	if [ -z "$(ucr get samba/share/netlogon/path)" -a -z "$(ucr get ucsschool/userlogon/netlogon/path)" ]; then
		univention-config-registry set \
			samba/share/netlogon/path=/var/lib/samba/netlogon \
			ucsschool/userlogon/netlogon/path=/var/lib/samba/netlogon/user
	fi
fi

univention-config-registry set \
	directory/manager/samba3/legacy?yes \
	listener/shares/rename?yes \
	samba4/join/dnsupdate?true \
	samba4/sysvol/sync/setfacl/AU?false

systemctl try-restart univention-directory-listener

#DEBHELPER#

exit 0
