62ucs-school-singlemaster.inst usr/lib/univention-install/
63ucs-school-portal-entry.inst usr/lib/univention-install/
ucsschool.png usr/share/univention-management-console-frontend/js/dijit/themes/umc/icons/50x50
ucsschool.svg usr/share/univention-management-console-frontend/js/dijit/themes/umc/icons/scalable
ucsschool_demo_pictures usr/share/ucs-school-metapackage/
create_demoportal.py usr/share/ucs-school-metapackage/scripts
var/www/univention/ucsschool var/www/univention/