#!/bin/sh
#
# UCS@school
#
# Copyright 2010-2015 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

. /usr/share/univention-lib/all.sh

univention-config-registry set \
	directory/manager/samba3/legacy?yes \
	connector/s4/mapping/sid_to_ucs?no \
	connector/s4/mapping/sid_to_s4?yes \
	listener/shares/rename?yes \
	samba4/join/dnsupdate?true \
	samba4/sysvol/sync/setfacl/AU?false \
	samba4/sysvol/sync/cron?"*/5 * * * *" \
	connector/s4/mapping/wmifilter?yes \
	ucsschool/import/generate/policy/dhcp/dns/set_per_ou?true \
	ucs/web/overview/entries/service/teacherconsole/icon?"/univention-management-console/js/dijit/themes/umc/icons/50x50/ucsschool.png" \
	ucs/web/overview/entries/service/teacherconsole/label?"UCS@school" \
	ucs/web/overview/entries/service/teacherconsole/label/de?"UCS@school" \
	ucs/web/overview/entries/service/teacherconsole/description?"Access to the UCS@school modules in the Univention Management Console" \
	ucs/web/overview/entries/service/teacherconsole/description/de?"Zugriff auf die UCS@school Module in der Univention Management Console" \
	ucs/web/overview/entries/service/teacherconsole/link?"/univention-management-console" \
	ucs/web/overview/entries/service/teacherconsole/priority?"10"

if dpkg --compare-versions "$2" lt 6.0.8-8 ; then
	# Bug #34831
	if [ "$(ucr get ucs/web/overview/entries/service/teacherconsole/icon)" = "/univention-management-console/js/dijit/themes/umc/icons/50x50/univention-management-console.png" ]; then
		ucr set ucs/web/overview/entries/service/teacherconsole/icon="/univention-management-console/js/dijit/themes/umc/icons/50x50/ucsschool.png"
	fi
fi

if [ "$1" = "configure" -a -n "$2" ]; then
	if dpkg --compare-versions "$2" lt 5.0.2-1 ; then
		eval "$(ucr shell)"

		if [ -n "$domainname" ]; then
			ucr unset connector/s4/mapping/dns/srv_record/_ldap._tcp.$domainname/location \
					connector/s4/mapping/dns/srv_record/_ldap._tcp.pdc._msdcs.$domainname/location \
					connector/s4/mapping/dns/srv_record/_ldap._tcp.dc._msdcs.$domainname/location \
					connector/s4/mapping/dns/srv_record/_ldap._tcp.gc._msdcs.$domainname/location \
					connector/s4/mapping/dns/srv_record/_gc._tcp.$domainname/location \
					connector/s4/mapping/dns/srv_record/_kerberos._tcp.$domainname/location \
					connector/s4/mapping/dns/srv_record/_kerberos._udp.$domainname/location \
					connector/s4/mapping/dns/srv_record/_kerberos-adm._tcp.$domainname/location \
					connector/s4/mapping/dns/srv_record/_kerberos._tcp.dc._msdcs.$domainname/location \
					connector/s4/mapping/dns/srv_record/_kpasswd._tcp.$domainname/location \
					connector/s4/mapping/dns/srv_record/_kpasswd._udp.$domainname/location \
					connector/s4/mapping/dns/srv_record/_kerberos._tcp.default-first-site-name._sites.dc._msdcs.$domainname/location \
					connector/s4/mapping/dns/srv_record/_kerberos._tcp.default-first-site-name._sites.$domainname/location \
					connector/s4/mapping/dns/srv_record/_ldap._tcp.default-first-site-name._sites.gc._msdcs.$domainname/location \
					connector/s4/mapping/dns/srv_record/_ldap._tcp.default-first-site-name._sites.dc._msdcs.$domainname/location \
					connector/s4/mapping/dns/srv_record/_ldap._tcp.default-first-site-name._sites.$domainname/location \
					connector/s4/mapping/dns/srv_record/_gc._tcp.default-first-site-name._sites.$domainname/location
		fi
	fi

	if dpkg --compare-versions "$2" lt 6.0.7-26 ; then
		## for ucs-school-import and ucs-school-umc-groups
		univention-config-registry set \
			ucsschool/import/roleshare=no \
			update/reboot/required=yes
	fi
fi

/etc/init.d/univention-directory-listener crestart

call_joinscript 62ucs-school-master.inst

#DEBHELPER#

exit 0

