00ucs-school-app-version-check.inst usr/lib/univention-install/
62ucs-school-singlemaster.inst usr/lib/univention-install/
ucsschool.png usr/share/univention-management-console-frontend/js/dijit/themes/umc/icons/50x50
ucsschool.svg usr/share/univention-management-console-frontend/js/dijit/themes/umc/icons/scalable
app_version.py usr/share/ucs-school-metapackage/scripts
set_nt_acl_on_shares usr/share/ucs-school-metapackage/scripts
ucsschool-join-hook.py usr/share/ucs-school-metapackage/
create_demoportal.py usr/share/ucs-school-metapackage/scripts
