00ucs-school-app-version-check.inst usr/lib/univention-install/
62ucs-school-central-slave.inst usr/lib/univention-install/
63ucs-school-portal-entry.inst usr/lib/univention-install/
app_version.py usr/share/ucs-school-metapackage/scripts
ucsschool.png usr/share/univention-management-console-frontend/js/dijit/themes/umc/icons/50x50
ucsschool.svg usr/share/univention-management-console-frontend/js/dijit/themes/umc/icons/scalable
