#!/bin/sh
#
#

eval `univention-config-registry shell`

help() {
	echo ""
    echo "syntax: $0 <action> <dn>"
	echo "  <action> is one of --setpol, --unsetpol"
	echo "  --setpol    set policy"
	echo "  --unsetpol  remove policy"
	echo ""
	echo "current policy: $restoremanagement_policy"
}


if [ -z "$restoremanagement_policy" ] ; then
	echo "$0: ERROR: config-registry variable restoremanagement/policy is not set!"
	exit 1
fi

case $1 in
	--setpol)
		ACTION=SETPOL
		shift
		;;
	--unsetpol)
		ACTION=UNSETPOL
		shift
		;;
esac

if [ -z "$ACTION" ] ; then
    echo "$0: ERROR: no action given!"
	help
    exit 1
fi

if [ -z "$1" ] ; then
	echo "$0: ERROR: no host given!"
	help
	exit 2
fi

HOSTPASSWD=$(cat /etc/machine.secret)

while [ -n "$1" ] ; do
	DN="$1"
	shift

	# find corresponding dhcp object
	OK=1
	HOSTDATA=$(ldapsearch -LLL -x -b $DN aRecord macAddress)
	ARECORD=$(echo "$HOSTDATA" | grep "aRecord" | sed -e 's|aRecord: ||')
	MACADDR=$(echo "$HOSTDATA" | grep "macAddress" | sed -e 's|macAddress: ||')
	if [ -z "$ARECORD" -o -z "$MACADDR" ] ; then
		echo "$0: ERROR: aRecord or macAddress is not set for host $DN"
		OK=0
	fi

	if [ "$OK" = "1" ] ; then
		DHCPDN=$(ldapsearch -LLL -x "(&(objectClass=univentionDhcpHost)(univentionDhcpFixedAddress=$ARECORD)(dhcpHWAddress=ethernet $MACADDR))" dn | sed -e 's|dn: ||')
		if [ -z "$DHCPDN" ] ; then
			echo "$0: ERROR: cannot find dhcp object for host $DN"
			OK=0
		fi
		POLICYSTATUS=$(ldapsearch -LLL -x -b $DHCPDN "(univentionPolicyReference=$restoremanagement_policy)" dn)
	fi

	if [ "$ACTION" = "SETPOL" -a "$OK" = "1" ] ; then
		if [ -z "$POLICYSTATUS" ] ; then
		    # set policy and reset flag
			univention-directory-manager dhcp/host modify --binddn "$ldap_hostdn" --bindpwd "$HOSTPASSWD" --dn $DHCPDN --policy-reference "$restoremanagement_policy"
		else
			echo "$0: INFO: policy already set"
		fi
	fi

	if [ "$ACTION" = "UNSETPOL" -a "$OK" = "1" ] ; then
		if [ -n "$POLICYSTATUS" ] ; then
		    # remove policy
			univention-directory-manager dhcp/host modify --binddn "$ldap_hostdn" --bindpwd "$HOSTPASSWD" --dn $DHCPDN --policy-dereference "$restoremanagement_policy"
		else
			echo "$0: INFO: cannot remove policy - wasn't set"
		fi
	fi
done
