#!/bin/sh

#DEBHELPER#

eval `univention-config-registry shell ldap/base server/role`

if [ "$server_role" = "domaincontroller_master" ] || [ "$server_role" = "domaincontroller_backup" ]; then
	/usr/lib/univention-install/38univention-management-console-distribution.inst || true
fi

univention-config-registry set umc/datadistribution/datadir/sender?Unterrichtsmaterial \
								umc/datadistribution/datadir/recipient?Unterrichtsmaterial \
								umc/datadistribution/debug/level?2 \
								php/limit/postsize=20 \
								php/limit/filesize=10

exit 0
