#!/usr/share/ucs-test/runner bash
## desc: In-container integration tests for the ID Brokers Provisioning API
## exposure: dangerous
## tags: [ucsschool-id-broker]
## packages: [id-broker-provisioning-api-plugin]
## external-junit: /tmp/id_broker_provisioning_in_container_integration_tests.xml

APP="ucsschool-apis"
PLUGIN_DIR="/var/lib/univention-appcenter/apps/ucsschool-apis/data/plugins/id-broker-provisioning-api"
TEST_DIR="tests/integration_tests"
CMD="cd $PLUGIN_DIR; python3 -m pytest -l -v --junit-xml=/tmp/junit.xml --junit-prefix=96_ucsschool-id-broker.02_in_container_integration_tests_provisioning $TEST_DIR"

if ! univention-app shell ucsschool-apis pytest --help >/dev/null; then
  echo "Installing testing packages..."
  univention-app shell "$APP" python3 -m pip install -U pip wheel
  univention-app shell "$APP" python3 -m pip install poetry
  univention-app shell "$APP" sh -c "cd $PLUGIN_DIR; poetry export -f requirements.txt --output requirements.txt --dev --without-hashes"
  univention-app shell "$APP" python3 -m pip uninstall --yes poetry
  univention-app shell "$APP" python3 -m pip install -r $PLUGIN_DIR/requirements.txt
fi

echo "Running in container of app '$APP': sh -c \"$CMD\""

univention-app shell "$APP" sh -c "$CMD"
rm -f /tmp/id_broker_provisioning_in_container_integration_tests.xml

univention-app shell "$APP" cat /tmp/junit.xml > /tmp/id_broker_provisioning_in_container_integration_tests.xml
