#!/bin/sh
#
# Univention Management Console Module printermoderation
#
# Copyright 2015-2024 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

# shellcheck source=/dev/null
. /usr/share/univention-lib/all.sh

eval "$(ucr shell)"

ret=0

# set default windows driver for pdf printer
# is_ucr_true
#  -> 0 if true
#  -> 1 if false
#  -> 2 is unset
is_ucr_true "ucsschool/printermoderation/windows/driver/assign"
assign_driver=$?
if { [ $assign_driver -eq 0 ] || [ $assign_driver -eq 2 ]; } && [ -n "$ucsschool_printermoderation_windows_driver_name" ]; then
    # once Bug #24075 is fixed, we can remove this update group
    # stuff here, instead we can simply add the samba printer privileges
    # to the machine account

    # check if credentials are passed
    ucs_parseCredentials "$@"
    if [ "${server_role:?}" = "domaincontroller_slave" ] ; then
        if [ -z "$binddn" ] || { [ -z "$bindpwd" ] && [ -z "$bindpwdfile" ]; }; then
	    echo "usage: $0 --binddn DN --bindpwd Password or --bindpwdfile FILE"
	    exit 2
	fi
    fi
    group="Printer-Admins"
    if [ -n "$groups_default_printoperators" ]; then
        group="$groups_default_printoperators"
    fi
    if is_ucr_true "connector/s4/mapping/sid_to_s4"; then
        for i in $(seq 1 300); do
            # Wait for sid mapping from ucs to avoid a broken group, bug #57219
            host_sid_ldap=$(univention-ldapsearch -LLL -b "${ldap_hostdn:?}" sambaSID | grep sambaSID | sed 's/sambaSID: //g')
            host_sid_s4=$(univention-s4search dNSHostName="$(hostname -f)" objectSid | grep objectSid | sed 's/objectSid: //g')
            if [ "$host_sid_ldap" = "$host_sid_s4" ]; then
                break
            fi
            sleep 1
        done
        if [ "$i" -ge 300 ]; then
            echo "objectSID for $ldap_hostdn differ in ldap and samba4 database."
            echo "Try rerunning this script later or skip it by setting: "
            echo "'ucr set ucsschool/printermoderation/windows/driver/assign=no'"
            exit 2
        fi
    fi
    if ! univention-ldapsearch cn="$group" | ldapsearch-wrapper| grep -q "memberUid: ${hostname:?}\$"; then
        # add machine account to printer group
        udm groups/group modify "$@" --ignore_exists \
                --dn "cn=$group,cn=groups,${ldap_base:?}" \
                --append hosts="$ldap_hostdn" || exit $?
        remove="$group"
    fi
    # wait for printer
    echo "Setting windows printer driver for PDFDrucker ..."
    for _ in $(seq 1 300); do
        sleep 1
        if rpcclient -P -c 'enumprinters' "$hostname" | grep -q "\\\\PDFDrucker"; then
            rpcclient -P -c "setdriver PDFDrucker '$ucsschool_printermoderation_windows_driver_name'" "$hostname"
            ret=$?
            if [ "$ret" -eq 0 ]; then
                break
            fi
        fi
    done
    # remove machine account from printer group
    if [ -n "$remove" ]; then
        udm groups/group modify "$@" --ignore_exists \
            --dn "cn=$remove,cn=groups,$ldap_base" \
            --remove hosts="$ldap_hostdn"
    fi
fi

exit $ret
