#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
# Univention Management Console module:
#   Control computers of pupils in a room
#
# SPDX-FileCopyrightText: 2012-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

import subprocess
from argparse import ArgumentParser

import univention.admin.uexceptions as udm_exceptions
from ucsschool.lib.models.group import ComputerRoom
from univention.admin.uldap import getMachineConnection
from univention.config_registry import ConfigRegistry, handler_set, handler_unset
from univention.management.console.modules.computerroom import reset_room_settings


def deactivate_rules(roomDN):
    lo, po = getMachineConnection()
    try:
        room = ComputerRoom.from_dn(roomDN, None, lo)
    except udm_exceptions.noObject:
        return
    hosts = []
    for pc in room.get_computers(lo):
        hosts += pc.ip_address
    reset_room_settings(room.get_relative_name(), hosts)
    # reload cups
    subprocess.call(["/bin/systemctl", "reload", "cups.service"])  # nosec


def deprecated_deactivate_rules(options):
    ucr = ConfigRegistry()
    ucr.load()

    hosts = set(options.hosts)
    vset = {}

    # extract values
    for variable in options.extract:
        if ucr.get(variable):
            old = set(ucr[variable].split(" "))
        else:
            old = set()
        new = old.difference(hosts)
        if new:
            vset[variable] = " ".join(new)
        else:
            options.remove.append(variable)

    handler_set(["%s=%s" % x for x in vset.items()])

    # remove values
    handler_unset(options.remove)

    # reload cups
    if not subprocess.call(["/bin/systemctl", "is-active", "--quiet", "cups.service"]):  # nosec
        subprocess.call(["/bin/systemctl", "reload", "cups.service"])  # nosec


if __name__ == "__main__":
    parser = ArgumentParser()

    parser.add_argument("-r", "--remove", action="append", default=[])  # Deprecated
    parser.add_argument("-e", "--extract", action="append", default=[])  # Deprecated
    parser.add_argument("-o", "--room", action="append", dest="rooms", default=[])
    parser.add_argument("hosts", nargs="*")

    options = parser.parse_args()

    for room in options.rooms:
        deactivate_rules(room)
    else:
        deprecated_deactivate_rules(options)
