#!/bin/sh
# postrm script for ucs-school-branding
#
# SPDX-FileCopyrightText: 2012-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

# remove diversions for template.html and all branding.json files
prefix='/usr/share/univention-management-console-frontend/js/umc'
for iFile in $prefix/app/help.*.html.ucs $prefix/i18n/*/branding.json.ucs; do
	iFile=$(echo $iFile | awk '{ gsub(/\.ucs$/, "", $0); print }') # remove .ucs suffix
	dpkg-divert --rename --remove "$iFile"
done

#DEBHELPER#

exit 0


