#!/bin/sh
# preinst script for ucs-school-branding
#
# SPDX-FileCopyrightText: 2012-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

# divert template.html and all branding.json files
prefix='/usr/share/univention-management-console-frontend/js/umc'
for iFile in $prefix/app/help.de.html $prefix/app/help.en.html $prefix/i18n/*/branding.json; do
	dpkg-divert --package ucs-school-branding --rename --divert "$iFile.ucs" "$iFile" || true
done

#DEBHELPER#

exit 0


