#!/bin/sh
#
# Univention Webui Style Customized
#
# Copyright (C) 2008 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# Binary versions of this file provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

dpkg-divert --package univention-webui-style-customized --add --rename --divert /usr/share/univention-webui-style/style/category_activearrow.gif.orig /usr/share/univention-webui-style/style/category_activearrow.gif || true
dpkg-divert --package univention-webui-style-customized --add --rename --divert /usr/share/univention-webui-style/style/logo_univention.gif.orig /usr/share/univention-webui-style/style/logo_univention.gif || true
dpkg-divert --package univention-webui-style-customized --add --rename --divert /usr/share/univention-webui-style/style/reiter_graurot18x24.gif.orig /usr/share/univention-webui-style/style/reiter_graurot18x24.gif || true
dpkg-divert --package univention-webui-style-customized --add --rename --divert /usr/share/univention-webui-style/style/reiter_rot18x24.gif.orig /usr/share/univention-webui-style/style/reiter_rot18x24.gif || true
dpkg-divert --package univention-webui-style-customized --add --rename --divert /usr/share/univention-webui-style/style/reiter_rotgrau18x24.gif.orig /usr/share/univention-webui-style/style/reiter_rotgrau18x24.gif || true
dpkg-divert --package univention-webui-style-customized --add --rename --divert /usr/share/univention-webui-style/style/slogan_whitebg.gif.orig /usr/share/univention-webui-style/style/slogan_whitebg.gif || true
dpkg-divert --package univention-webui-style-customized --add --rename --divert /usr/share/univention-webui-style/style/stylesheet.css.orig /usr/share/univention-webui-style/style/stylesheet.css || true

#DEBHELPER#

exit 0

