#!/bin/sh
#
# UCS@school UMC module schoolexam-master
#  postinst script
#
# SPDX-FileCopyrightText: 2007-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

eval "$(univention-config-registry shell)"

if [ "$1" = configure ] && dpkg --compare-versions "$2" lt-nl 6.0.10-1; then
	ucr set 'ucsschool/exam/user/ldap/blacklist'="$ucsschool_exam_user_ldap_blacklist|ucsschoolSourceUID|ucsschoolRecordUID"
fi

ucr set \
	'ucsschool/exam/user/ldap/blacklist?mail|mailPrimaryAddress|mailAlternativeAddress|ucsschoolSourceUID|ucsschoolRecordUID' \
	'ucsschool/exam/cron/cleanup-master/options?--skip-exam-shutdown --skip-ucr-cleanup --skip-exam-cleanup --skip-room-cleanup'

exit 0
