#!/bin/sh
#
# UCS@school UMC module schoolexam
#  postinst script
#
# SPDX-FileCopyrightText: 2015-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

eval "$(univention-config-registry shell)"

ucr set ucsschool/exam/default/checkbox/distribution?true

if [ "$1" = configure ] && dpkg --compare-versions "$2" lt-nl 9.0.0-9; then
 	univention-config-registry unset ucsschool/exam/user/homedir/autoremove
fi

if [ "$1" = configure ] && dpkg --compare-versions "$2" lt 9.0.1-20; then
 	univention-config-registry set ucsschool/exam/default/show/restart=yes
fi

exit 0
