#!/usr/share/ucs-test/runner bash
## desc: run tests in container which are supplied by the ucsschool.lib
## tags: [ucs_school_kelvin]
## exposure: dangerous
## packages: []
## bugs: []
## external-junit: /tmp/kelvin-ucsschool-lib_in_container_integration_tests.xml


APP="ucsschool-kelvin-rest-api"

declare -a CMD=(sh -c "
cd /kelvin/ucs-school-lib/modules &&
python3 -m pytest --reruns 1 --reruns-delay 5 --junit-xml=/tmp/junit.xml --junit-prefix=94_ucsschool-api-kelvin.10_in_container_tests_ucsschool_lib")


echo "Running in container: ${CMD[@]}"

univention-app shell "$APP" "${CMD[@]}" || (rv=$?; pkill -f '^/usr/bin/python.*pytest$'; exit $rv)
rm -f /tmp/kelvin-ucsschool-lib_in_container_integration_tests.xml
univention-app shell "$APP" cat /tmp/junit.xml > /tmp/kelvin-ucsschool-lib_in_container_integration_tests.xml
