#!/usr/share/ucs-test/runner bash
## desc: run linting tests in container which are supplied by the kelvin api
## tags: [ucs_school_kelvin]
## exposure: dangerous
## packages: []
## bugs: []

APP="ucsschool-kelvin-rest-api"
declare -a CMD=(sh -c '
cd /kelvin/kelvin-api &&
make lint-coverage')

echo "Running in container: ${CMD[@]}"
univention-app shell "$APP" "${CMD[@]}" || (rv=$?; pkill -f '^/usr/bin/python.*pytest$'; exit $rv)
