#! /bin/sh
#
# Univention Squid
#  postinst script
#
# Copyright (C) 2004, 2005, 2006 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# Binary versions of this file provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

set -e

#DEBHELPER#

case "$1" in
    configure)
		/etc/init.d/univention-directory-listener crestart

		eval `univention-config-registry shell`
		univention-config-registry set proxy/redirect=squidguard \
									proxy/force=no \
									proxy/ldapauth=no \
									proxy/ntlmauth=yes \
									proxy/basicauth=yes \
									samba/winbind/trusted/domains/only=no \
									samba/logonscript?univention-netlogon-proxy.vbs \
									proxy/filter/redirecttarget?"http://$hostname.$domainname/blocked-by-squid.html" \
									proxy/filter/domain/whitelisted/1?"www.univention.de"

		# set correct permissions
		dpkg-statoverride --update --force --add root proxy 750 /var/run/samba/winbindd_privileged/ || true
		dpkg-statoverride --update --force --add root proxy 2770 /var/lib/sfb-squid-squidguard/ || true
		chown proxy:proxy /var/spool/squid/swap.* || true

		# init squidguard db
		touch /var/lib/sfb-squid-squidguard/whitelisted-domain || true
		touch /var/lib/sfb-squid-squidguard/whitelisted-url || true
		touch /var/lib/sfb-squid-squidguard/blacklisted-domain || true
		touch /var/lib/sfb-squid-squidguard/blacklisted-url || true
		chown root:proxy /var/lib/sfb-squid-squidguard/*listed-* || true
		/usr/bin/squidGuard -C all || true
		chmod ug+rw /var/lib/sfb-squid-squidguard/*listed-* || true

		univention-config-registry commit /etc/init.d/winbind

		/etc/init.d/samba reload
		/etc/init.d/winbind restart
		/etc/init.d/squid restart
		;;

    abort-upgrade|abort-remove|abort-deconfigure)
		;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
		;;
esac

exit 0
