#!/usr/bin/python2.7
# -*- coding: utf-8 -*-
#
# Univention UCS@school
#
# Copyright 2018-2019 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

import sys, os, django, subprocess
from univention.admin.uldap import explodeDn

ou = explodeDn(sys.argv[2], 1)[0]

# setup Django
sys.path.append('/usr/share/pyshared/ucsschool/http_api/')
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "app.settings")
django.setup()

# create Django School object
from ucsschool.http_api.import_api.models import School
try:
	School.update_from_ldap(ou)
except RuntimeError as exc:
	# handle running in other Django app process
	print('Falling back to "manage.py updateschools", because: {}'.format(exc))
	subprocess.call(['/usr/bin/python', '/usr/share/pyshared/ucsschool/http_api/manage.py', 'updateschools', '--ou', ou])
