#!/usr/share/ucs-test/runner python
## desc: Check ucschool import counter diagnose module
## tags: [ucsschool, diagnostic_test]
## roles: [domaincontroller_master]
## exposure: dangerous
## packages:
##   - ucs-school-import
## bugs: [50500]

import copy
from ldap.filter import filter_format
import univention.testing.strings as uts
import univention.testing.utils as utils
from univention.testing.ucs_samba import wait_for_drs_replication
from univention.testing.ucsschool.importusers_cli_v2 import UniqueObjectTester
from univention.testing.ucsschool.importusers import Person

import subprocess
from univention.management.console.config import ucr
from univention.uldap import getAdminConnection


class Test(UniqueObjectTester):
	def __init__(self):
		super(Test, self).__init__()
		self.ou_B = None

	def test(self):
		"""
		Test creation of email addresses from a special scheme (Bug #44993).
		"""
		config = copy.deepcopy(self.default_config)
		config.update_entry('csv:mapping:record_uid', 'record_uid')
		config.update_entry('csv:mapping:role', '__role')
		config.update_entry('user_role', None)
		del config['csv']['mapping']['E-Mail']
		scheme = "COUNTER2"
		# The module searches for all users with an ucsschoolRole:
		# '(&(univentionObjectType=users/user)(ucsschoolRole=*))'
		# so it suffices to only check against one.
		role = 'student'
		source_uid = 'source_uid-%s' % (uts.random_string(),)
		config.update_entry('source_uid', source_uid)
		self.log.info('*** Importing a user of each role and email scheme ', scheme)
		config.update_entry(
			'scheme:email',
			'<:umlauts><firstname>[0].<lastname>[{}]@{}'.format(scheme, self.maildomain)
		)
		config.update_entry(
			'scheme:username:default',
			'<:umlauts><firstname>[0].<lastname>[{}]'.format(scheme)
		)
		person_list = []
		for i in range(6):
			person = Person(self.ou_A.name, role)
			person.update(record_uid=uts.random_name(), source_uid=source_uid, username=None, mail=None)
			person.email_prefix = None
			person_list.append(person)

		fn_csv = self.create_csv_file(person_list=person_list, mapping=config['csv']['mapping'])
		config.update_entry('input:filename', fn_csv)
		fn_config = self.create_config_json(config=config)
		self.save_ldap_status()
		self.run_import(['-c', fn_config, '-i', fn_csv])
		self.check_new_and_removed_users(6, 0)
		for person in person_list:
			person.update_from_ldap(self.lo, ['dn', 'username', 'mail'])
			self.log.debug('person.dn=%r person.username=%r person.mail=%r', person.dn, person.username, person.mail)
			wait_for_drs_replication(filter_format('cn=%s', (person.username,)))
			person.verify()

		for person in person_list:
			person.update_from_ldap(self.lo, ['dn', 'username', 'mail'])
			self.log.debug('person.dn=%r person.username=%r person.mail=%r', person.dn, person.username, person.mail)
			wait_for_drs_replication(filter_format('cn=%s', (person.username,)))
			person.verify()

			person.email_prefix = '{}.{}'.format(person.firstname[0], person.lastname)
			self.log.info("Calculated person.email_prefix is %r.", person.email_prefix)
			self.unique_basenames_to_remove.append(person.email_prefix)
			person.update(mail='{}{}@{}'.format(person.email_prefix, '', self.maildomain))
			self.log.debug('person.dn=%r person.username=%r person.mail=%r', person.dn, person.username, person.mail)
			person.verify()
			self.check_unique_obj('unique-email', person.email_prefix, '2')

			person.username_prefix = '{}.{}'.format(person.firstname[0], person.lastname)
			self.log.info("Calculated person.username_prefix is %r.", person.username_prefix)
			self.unique_basenames_to_remove.append(person.username_prefix)
			if person.username != "{}{}".format(person.username_prefix, ""):
				self.fail('username %r is not expected string "%s%s"' % (person.username, person.username_prefix, "1" if scheme == "ALWAYSCOUNTER" else ""))
			self.log.info('Username %r is expected with string "%s%s"', person.username, person.username_prefix, "1" if scheme == "ALWAYSCOUNTER" else "")
			self.check_unique_obj('unique-usernames', person.username_prefix, '2')

		lo = getAdminConnection()
		uids = []
		for i, person in enumerate(person_list):
			if i == 0:
				new_mail = '{}{}@{}'.format(person.email_prefix, 3, self.maildomain)
				change = [('mailPrimaryAddress', person.mail, new_mail)]
				obj_dn = person.dn
			elif i == 1:
				new_uid = '{}{}'.format(person.username_prefix, 3)
				change = [('uid', person.username, new_uid)]
				obj_dn = person.dn
			else:
				unique_obj = 'unique-email' if i % 2 == 0 else 'unique-usernames'
				if i < 4:
					new_value = ['0']
				else:
					new_value = []
				obj_list = lo.searchDn(
					base='cn={},cn=ucsschool,cn=univention,{}'.format(unique_obj,ucr.get('ldap/base')),
					filter='cn={}'.format(person.username), scope='one')
				obj_dn = obj_list[0]
				change = [('ucsschoolUsernameNextNumber', ['2'], new_value)]

			lo.modify(obj_dn, change)
			self.log.info('change {}: {}'.format(obj_dn,change))
			uids.append(person.username)

	# Run diagnostic tool, capture and test if exceptions were thrown.
		args = ['/root/ucs-school-umc-diagnostic/umc/python/diagnostic/plugins/901_ucsschool_import_counter.py']
		# args = ['univention-run-diagnostic-checks', '-t', '901_ucsschool_import_counter.py']
		process = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
		errors = process.stderr.read()
		self.log.info('altered {} ldap-objects'.format(len(uids)))
		if not errors:
			raise Exception('diagnose-module did not find any false values!')
		# Search for uids, because if uid mailPrimaryAddress are changed,
		# I get the unique-mail/usernames object, but the uid is still in there.
		for uid in uids:
			if uid not in errors:
				raise Exception('diagnose-module did not find false value of {}.'.format(uid))
			else:
				self.log.info('diagnose-module did find false value of {}'.format(uid))


if __name__ == '__main__':
	Test().run()