#!/usr/share/ucs-test/runner python
# -*- coding: ISO8859-1 -*-
# -*- coding: utf-8 -*-
## desc: distribute materials with encoding
## roles: [domaincontroller_master, domaincontroller_backup, domaincontroller_slave, memberserver]
## tags: [apptest,ucsschool]
## versions:
##  4.0-0: skip
## exposure: dangerous
## packages: [ucs-school-umc-distribution]

from essential.distribution import Distribution
from essential.workgroup import Workgroup
from univention.lib.umc_connection import UMCConnection
import univention.testing.strings as uts
import univention.testing.ucr as ucr_test
import univention.testing.ucsschool as utu
import univention.testing.utils as utils

def main():
	with utu.UCSTestSchool() as schoolenv:
		with ucr_test.UCSTestConfigRegistry() as ucr:
			host = ucr.get('hostname')
			con = UMCConnection(host)

			# Create ou, teacher, student, group
			school, oudn = schoolenv.create_ou(name_edudc=ucr.get('hostname'))
			tea, teadn = schoolenv.create_user(school, is_teacher=True)
			stu, studn = schoolenv.create_user(school)
			group = Workgroup(school, members=[studn])
			group.create()
			utils.wait_for_replication_and_postrun()

			filename1 = "%s%s%s%s" % (
					u'Ä'.encode('UTF-8') ,
					uts.random_name_special_characters(3),
					u'→'.encode('UTF-8'),
					uts.random_name_special_characters(3),
					)
			filename2 = "%s%s%s" % (
					uts.random_name_special_characters(3),
					u'Ä'.encode('ISO8859-1'),
					uts.random_name_special_characters(3),
					)
			filename3 = uts.random_name()
			con.auth(tea, 'univention')

			# Create new project
			project = Distribution(
					school,
					sender=tea,
					umcConnection=con,
					ucr=ucr,
					files=[filename1, filename2, filename3],
					recipients=[group],
					flavor='teacher')
			project.add()
			project.check_add()
			project.distribute()
			project.check_distribute([stu])
			project.collect()
			project.check_collect([stu])

			project.remove()
			project.check_remove()


if __name__ == '__main__':
	main()
