#!/usr/share/ucs-test/runner python
## -*- coding: utf-8 -*-
## desc: test FormatPyHook
## tags: [apptest,ucsschool,skip_in_multiserver,ucsschool_import]
## roles: [domaincontroller_master]
## exposure: dangerous
## packages:
##   - ucs-school-import
## bugs: [42144, 45524]

import os
import sys
import copy
import random
import shutil
import datetime
from ldap.filter import escape_filter_chars
import univention.testing.strings as uts
from univention.testing.ucs_samba import wait_for_drs_replication
from essential.importusers_cli_v2 import CLI_Import_v2_Tester
from essential.importusers import Person


TESTHOOKSOURCE = CONFIG = os.path.join(os.path.dirname(__file__), 'testformathookpy')
TESTHOOKTARGET = '/usr/share/ucs-school-import/pyhooks/testformathook.py'


class Test(CLI_Import_v2_Tester):
	def __init__(self):
		super(Test, self).__init__()
		self.ou_B = None
		self.ou_C = None
		self.log.info('*** Copying %r to %r...', TESTHOOKSOURCE, TESTHOOKTARGET)
		shutil.copy2(TESTHOOKSOURCE, TESTHOOKTARGET)
		sys.path.append('/usr/share/ucs-school-import/pyhooks/')

	def cleanup(self):
		for ext in ['', 'c', 'o']:
			try:
				os.remove('{}{}'.format(TESTHOOKTARGET, ext))
				self.log.info('*** Deleted %s%s.', TESTHOOKTARGET, ext)
			except OSError:
				self.log.warn('*** Could not delete %s%s.', TESTHOOKTARGET, ext)
		super(Test, self).cleanup()

	def test(self):
		"""
		Bug #42144 / #45524: create users and check if the FormatTestPyHook did do its job.
		"""
		source_uid = 'sourceUID-{}'.format(uts.random_string())
		config = copy.deepcopy(self.default_config)
		config.update_entry('csv:mapping:Benutzername', 'username')
		config.update_entry('csv:mapping:recordUID', 'record_uid')
		config.update_entry('csv:mapping:role', '__type')
		config.update_entry('csv:mapping:birthday', 'birthday')
		# required to make ImportUser.make_birthday() run format_from_scheme():
		config.update_entry('scheme:birthday', '<birthday>')
		config.update_entry('scheme:email', '<firstname:lower>.<lastname:lower>@<maildomain>'),
		config.update_entry('scheme:recordUID', '<record_uid>')
		config.update_entry('sourceUID', source_uid)
		config.update_entry('user_role', None)
		config.update_entry('classes:reader', 'ucsschool.importer.reader.test_csv_reader.TestCsvReader')

		self.log.info('Importing a user from each role...')
		person_list = list()
		for role in ('student', 'teacher', 'staff', 'teacher_and_staff'):
			person = Person(self.ou_A.name, role)
			record_uid = 'recordUID-%s' % (uts.random_string(),)
			person.update(
				record_uid=record_uid,
				source_uid=source_uid,
				firstname=uts.random_username(),
				lastname=uts.random_username(),
				mail=None,
				birthday='{}-{:02}-{:02}'.format(random.randint(1900, 2016), random.randint(1, 12), random.randint(1, 27)),
			)
			if person.role in ('staff', 'student'):
				person._bday = person.birthday
				person.update(birthday=datetime.datetime.strptime(person.birthday, '%Y-%m-%d').strftime('%Y.%b.%d'))
			person_list.append(person)
		fn_csv = self.create_csv_file(person_list=person_list, mapping=config['csv']['mapping'])
		config.update_entry('input:filename', fn_csv)
		fn_config = self.create_config_json(values=config)
		self.save_ldap_status()
		self.run_import(['-c', fn_config])
		wait_for_drs_replication('cn={}'.format(escape_filter_chars(person_list[-1].username)))
		self.check_new_and_removed_users(4, 0)

		for person in person_list:
			if person.role in ('staff', 'student'):
				person.update(birthday=person._bday)
			email_local = '{}.{}'.format(person.firstname, person.lastname).lower()
			if person.role in ('student', 'teacher', 'teacher_and_staff'):
				email_local = email_local.translate(None, 'aeiou')
			person.update(mail='{}@{}'.format(email_local, self.maildomain))
			person.verify()
		self.log.info('*** OK: All %r users were created correctly.', len(person_list))


def main():
	tester = Test()
	try:
		tester.run()
	finally:
		tester.cleanup()


if __name__ == '__main__':
	main()
