#!/usr/share/ucs-test/runner python
## desc: Check diagnostic tool: ucschool slave groupmemberships
## roles: [domaincontroller_master]
## tags: [ucsschool,diagnostic_test]
## exposure: dangerous
## packages: [ucs-school-import]

# Checks if the domaincontroller slave and memberserver objects are members
# of both groups:
#   DC-Edukativnetz + OU-$OU-DC-Edukativnetz
# or
#   DC-Verwaltungsnetz + OU-$OU-DC-Verwaltungsnetz
# or
#   Member-Edukativnetz + OU-$OU-Member-Edukativnetz
# or
#   Member-Verwaltungsnetz + OU-$OU-Member-Verwaltungsnetz


"""
I removed a slave-dc from group dc-edukativnetz and got the following:

----------------------------------------
The following objects have faulty group memberships:
  cn=ucs-4064,cn=dc,cn=server,cn=computers,ou=testschool1,dc=wenzel-univention,dc=intranet
    - Host object is member in global edu group but not in OU specific slave group (or the other way around)
----------------------------------------

Added member-edukativ to OUtestschool1-Member-Verwaltungsnetz and (afterwards) DC-Verwaltungsnetz.
Both correctly raised this error:

----------------------------------------
The following objects have faulty group memberships:
    - Host object is member in edu groups AND in admin groups which is not allowed
----------------------------------------

I added the slave to the memberserver group:

----------------------------------------
The following objects have faulty group memberships:
  cn=ucs-4064,cn=dc,cn=server,cn=computers,ou=testschool1,dc=wenzel-univention,dc=intranet
    - Host object is member in global edu group but not in OU specific memberserver group (or the other way around)
    - Slave object is member in memberserver groups
----------------------------------------

I added the Memberserver to the slave-group:

----------------------------------------
univention.management.console.modules.diagnostic.Warning: UCS@school Domaincontroller Slave objects rely on the membership within certain UCS@school LDAP groups.
Inconsistencies in these group memberships can trigger erratic behaviour of UCS@school.

The following objects have faulty group memberships:
  cn=ucs-8036,cn=computers,dc=wenzel-univention,dc=intranet
    - Host object is member in global edu group but not in OU specific slave group (or the other way around)
    - Memberserver object is member in slave groups

----------------------------------------

"""

from __future__ import absolute_import
from __future__ import print_function
import subprocess
from univention.testing.ucsschool.ucs_test_school import AutoMultiSchoolEnv, logger
from univention.testing.ucsschool.ucs_test_school import NameDnObj
import univention.testing.strings as uts


class UCSSchoolSchoolComputers(AutoMultiSchoolEnv):
	def __init__(self):
		pass

	def run_all_tests(self):  # type: () -> None
		pass


def main():
	with UCSSchoolSchoolComputers() as test_suite:
		test_suite.create_multi_env_school_objects()
		test_suite.run_all_tests()


if __name__ == '__main__':
	main()
