#!/usr/share/ucs-test/runner python
## -*- coding: utf-8 -*-
## desc: Import OU via CLI
## tags: [apptest,ucsschool,ucsschool_import4]
## roles: [domaincontroller_master]
## timeout: 14400
## exposure: dangerous
## packages:
##   - ucs-school-import

import os
import shutil
import univention.testing.ucsschool.importou as eio

HOOKS_DIR = '/usr/share/ucs-school-import/hooks/ou_create_post.d'
BACKUP_DIR = '/usr/share/ucs-school-import/hooks/ou_create_post.d.bak'

if __name__ == '__main__':
	try:
		# remove hooks to make things faster
		os.mkdir(BACKUP_DIR)
		for filename in os.listdir(HOOKS_DIR):
			shutil.move(os.path.join(HOOKS_DIR, filename), BACKUP_DIR)
		eio.import_ou_basics(use_cli_api=True, use_python_api=False)
		eio.import_ou_with_existing_dc(use_cli_api=True, use_python_api=False)
		eio.import_3_ou_in_a_row(use_cli_api=True, use_python_api=False)
	finally:
		# re-enable hooks
		for filename in os.listdir(BACKUP_DIR):
			shutil.move(os.path.join(BACKUP_DIR, filename), HOOKS_DIR)
		os.rmdir(BACKUP_DIR)
