#!/usr/share/ucs-test/runner python
## -*- coding: utf-8 -*-
## desc: Import computers via python API
## tags: [apptest,ucsschool]
## roles: [domaincontroller_master]
## exposure: dangerous
## packages:
##   - ucs-school-import

from essential.importcomputers import *

if __name__ == '__main__':
	import_computers_basics(use_cli_api=False, use_python_api=True)

