#!/usr/share/ucs-test/runner python
## -*- coding: utf-8 -*-
## desc: Import networks via CLI
## tags: [apptest,ucsschool,skip_in_multiserver]
## roles: [domaincontroller_master]
## exposure: dangerous
## packages:
##   - ucs-school-import

from essential.importnetworks import import_networks_basics

if __name__ == '__main__':
	import_networks_basics(use_cli_api=True, use_python_api=False)
