#!/usr/share/ucs-test/runner python
## -*- coding: utf-8 -*-
## desc: Import printers via python API
## tags: [apptest,ucsschool]
## roles: [domaincontroller_master]
## exposure: dangerous
## packages:
##   - ucs-school-import

from essential.importprinters import *
import sys


if __name__ == '__main__':
	# Not yet implemented
	sys.exit(137)

	import_printers_basics(use_cli_api=False, use_python_api=True)

