#!/usr/bin/make -f
MAIN := quickstart-ucsschool-de-4.1
STYLESHEET := univention_extdocs
quickstart-de%: lang := de

COMMON_DIR := ../../../doc-common/docbook
include $(COMMON_DIR)/Makefile

OPTIONS += --stringparam front.cover "$(CURDIR)/page-background-title-page.jpg"
