#!/usr/bin/python2.4 -OO
# Copyright 2007 Univention GmbH

import univention.test.ldapacls as utl

import locale, os, sys, string, time

from optparse import OptionParser


def main():
	utl.init()

	parser = OptionParser()
	for opt in utl.get_options():
		parser.add_option( opt )
	( options, args ) = parser.parse_args()
	utl.set_options( options )

	utl.prepare()
	utl.run()
	utl.cleanup()

if __name__ == "__main__":
	main()
