#!/bin/sh
#
# UCS@school UMC Distribution Module
#  postinst script
#
# SPDX-FileCopyrightText: 2007-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

eval "$(univention-config-registry shell)"

univention-config-registry set \
	ucsschool/datadistribution/datadir/sender?Unterrichtsmaterial \
	ucsschool/datadistribution/datadir/recipient?Unterrichtsmaterial \
	ucsschool/datadistribution/debug/level?2 \
	ucsschool/datadistribution/cache?/var/lib/ucs-school-umc-distribution \
	ucsschool/datadistribution/exclude_teachers?False

# make sure that the upload limit as at least 10 MB when the package is
# installed for the first time
if [ -z "$2" -a "$umc_server_upload_max" -lt 10240 ]; then
	univention-config-registry set umc/server/upload/max=10240
fi

exit 0
