36ucs-school-roles-udm.inst           usr/lib/univention-install/
schema/ucs-school-roles-udm.schema    usr/share/ucs-school-roles-udm/schema
udm/handlers/authorization/*.py       usr/lib/python2.7/dist-packages/univention/admin/handlers/authorization/
udm/handlers/authorization/*.py       usr/lib/python3/dist-packages/univention/admin/handlers/authorization/
udm/syntax.d/*.py       usr/lib/python2.7/dist-packages/univention/admin/syntax.d/
udm/syntax.d/*.py       usr/lib/python3/dist-packages/univention/admin/syntax.d/
