#!/bin/sh
#
# Univention UCS@school
#
# SPDX-FileCopyrightText: 2007-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

univention-config-registry set \
	ucsschool/listener/oldsharedir/targetdir?"/home/backup/groups/" \
	ucsschool/listener/oldsharedir/prefixes?"/home/"

# conditional restart of univention directory listener
systemctl try-restart univention-directory-listener

exit 0
