#!/bin/sh
#
# Univention Reservation Database
#  postinst file for this package
#
# Copyright 2008-2010 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

#DEBHELPER#

# set the root password
if [ ! -e /etc/mysql.secret ]; then
	tmp=$(mktemp)
	makepasswd --nocrypt > $tmp
	passwd=$(cat $tmp)
	hash=$(mkpasswd --hash=md5 -s < $tmp)
	touch /etc/mysql.secret
	chmod 600 /etc/mysql.secret
	echo $passwd > /etc/mysql.secret
	chown root /etc/mysql.secret
	rm -f $tmp
	# set passwd for database user reservation
	/usr/bin/mysqladmin -u root password "$passwd"
	unset passwd
fi

# create database during fresh installation
if [ "$1" = "configure" -a -z "$2" ] ; then
	mysql -f --password=$(cat /etc/mysql.secret) < /usr/share/ucs-school-reservation-database/datatbase.sql
	mysql -f --password=$(cat /etc/mysql.secret) < /usr/share/ucs-school-reservation-database/tables.sql
fi
# perform database update if previous package version is lower than 5.0.0
if [ "$1" = "configure" -a -n "$2" ] && dpkg --compare-versions "$2" lt 5.0.0; then
	mysql -f --password=$(cat /etc/mysql.secret) < /usr/share/ucs-school-reservation-database/tables-update-5.0.0.sql
fi


# create mysql user
if [ ! -e /etc/reservation-sql.secret ]; then
	tmp=$(mktemp)
	makepasswd --nocrypt > $tmp
	passwd=$(cat $tmp)
	hash=$(mkpasswd --hash=md5 -s < $tmp)
	touch /etc/reservation-sql.secret
	chmod 600 /etc/reservation-sql.secret
	echo $passwd > /etc/reservation-sql.secret
	chown www-data /etc/reservation-sql.secret
	rm -f $tmp
	# set passwd for database user reservation
	echo "SET PASSWORD FOR 'reservation' = PASSWORD('$passwd')" | mysql -u root --password=$(cat /etc/mysql.secret)
	unset passwd
fi

exit 0

