#!/bin/sh
#
# UCS@School
#  postinst script
#
# Copyright 2006-2010 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

#DEBHELPER#

case "$1" in
    configure)
		/etc/init.d/univention-directory-listener crestart

		# setting of some proxy/* UCR variables is required
		eval $(univention-config-registry shell)
		univention-config-registry set proxy/redirect=squidguard \
									proxy/force=no \
									proxy/ldapauth=no \
									proxy/ntlmauth=yes \
									proxy/basicauth=yes \
									samba/winbind/trusted/domains/only=no \
									samba/logonscript?univention-netlogon-proxy.vbs \
									proxy/filter/redirecttarget?"http://$hostname.$domainname/blocked-by-squid.html" \
									proxy/filter/domain/whitelisted/1?"www.univention.de" \
									"samba/global/options/winbind use default domain?yes" \
									"proxy/ntlmauth/children?10"


		# set correct permissions
		dpkg-statoverride --update --force --add root proxy 750 /var/run/samba/winbindd_privileged/ || true
		dpkg-statoverride --update --force --add root proxy 2770 /var/lib/ucs-school-webproxy/ || true
		chown proxy:proxy /var/spool/squid/swap.* || true

		# init squidguard db
		touch /var/lib/ucs-school-webproxy/whitelisted-domain || true
		touch /var/lib/ucs-school-webproxy/whitelisted-url || true
		touch /var/lib/ucs-school-webproxy/blacklisted-domain || true
		touch /var/lib/ucs-school-webproxy/blacklisted-url || true
		chown root:proxy /var/lib/ucs-school-webproxy/*listed-* || true
		/usr/bin/squidGuard -C all || true
		chmod ug+rw /var/lib/ucs-school-webproxy/*listed-* || true

		univention-config-registry commit /etc/init.d/winbind

		mkdir -p /var/run/squid/
		chown proxy:proxy /var/run/squid/

		/etc/init.d/samba reload
		sleep 2s
		/etc/init.d/winbind restart
		sleep 2s
		/etc/init.d/squid restart
		;;

    abort-upgrade|abort-remove|abort-deconfigure)
		;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
		;;
esac

exit 0
