#!/bin/sh
#
# UCS@school
#  postinst script
#
# SPDX-FileCopyrightText: 2006-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

eval "$(univention-config-registry shell)"


case "$1" in
    configure)
		echo "Restarting univention-directory-listener if running"
		deb-systemd-invoke try-restart univention-directory-listener

		# set correct permissions
		dpkg-statoverride --update --force-all --add root proxy 2770 /var/lib/ucs-school-webproxy || true
		dpkg-statoverride --update --force-all --add root proxy 2770 /var/lib/ucs-school-webproxy/bdbtemp || true

		if dpkg --compare-versions "$2" lt 11.0.6-1
		then
			univention-config-registry set 'squid/acl/windowsupdater/allow/dstdomain-i/regex?(.*\.update\.microsoft|download.windowsupdate)\.com'
		else
			if [ "$(ucr get squid/acl/windowsupdater/allow/dstdomain-i/regex)" = '^(.*\.update\.microsoft|download.windowsupdate)\.com$' ]
			then
				# fix old configuration (Bug #40960)
				univention-config-registry set 'squid/acl/windowsupdater/allow/dstdomain-i/regex=(.*\.update\.microsoft|download.windowsupdate)\.com'
			fi
		fi

		# Bug #47645: migrate proxy/pac/exclude/domains/domainnames to ../dnsnames
		if dpkg --compare-versions "$2" lt 14.0.0-7
		then
			ucrv_domainnames="$(ucr get proxy/pac/exclude/domains/domainnames)"
			ucrv_dnsnames="$(ucr get proxy/pac/exclude/domains/dnsnames)"
			if [ -z "$ucrv_dnsnames" ] && [ -n "$ucrv_domainnames" ]
			then
				echo "Migrating proxy/pac/exclude/domains/domainnames to proxy/pac/exclude/domains/dnsnames."
				ucr set proxy/pac/exclude/domains/dnsnames="$ucrv_domainnames"
				ucr unset proxy/pac/exclude/domains/domainnames
			elif [ -n "$ucrv_dnsnames" ] && [ -n "$ucrv_domainnames" ]
			then
				echo "Both UCR variables proxy/pac/exclude/domains/domainnames and"
				echo "proxy/pac/exclude/domains/dnsnames are set, but only"
				echo "proxy/pac/exclude/domains/dnsnames is supported."
				echo "Please migrate your settings and unset proxy/pac/exclude/domains/domainnames."
			fi
		fi

		# init squidguard db
		touch /var/lib/ucs-school-webproxy/whitelisted-domain || true
		touch /var/lib/ucs-school-webproxy/whitelisted-url || true
		touch /var/lib/ucs-school-webproxy/blacklisted-domain || true
		touch /var/lib/ucs-school-webproxy/blacklisted-url || true
		chown -c root:proxy /var/lib/ucs-school-webproxy/*listed-* || true
		/usr/bin/squidGuard -C all < /dev/null || true
		chmod -c ug+rw /var/lib/ucs-school-webproxy/*listed-* || true

		if systemctl is-active smbd > /dev/null; then
			echo "Restarting samba"
			deb-systemd-invoke reload smbd
			sleep 2
		fi

		if systemctl is-active winbind > /dev/null; then
			echo "Restarting winbind"
			deb-systemd-invoke restart winbind
			sleep 2
		fi

		if systemctl is-active squid > /dev/null; then
			echo "Restarting squid"
			deb-systemd-invoke restart squid
		fi

		a2ensite wpad.conf
		echo "Reloading apache"
		deb-systemd-invoke reload apache2

		univention-config-registry set \
			'proxy/filter/setting/Kein Internet/filtertype?whitelist-block' \
			'proxy/filter/setting/Unbeschränkt/filtertype?blacklist-pass' \
			'proxy/filter/setting/Unbeschränkt/wlan?true' \
			'proxy/filter/global/blacklists/forced?no' \
			'dhcpd/options/wpad/252=text'

		# Set dhcpd/authoritative=yes only for fresh installations.
		# This is needed for windows clients before Win 8 to accept the
		# "wpad" DHCP-option (Bug #40442).
		if [ -z "$2" ]; then
			univention-config-registry set 'dhcpd/authoritative=yes'
		fi

		# set variable on fresh installation and during update to version 10.0.3 (aka UCS@school 3.2R2)
		if dpkg --compare-versions "$2" lt 10.0.3 ; then
			ucr set squid/forwardedfor=on
		fi

		# shellcheck disable=SC2015
		dpkg --compare-versions "${2:-}" lt-nl 16.0.1 &&
			update-rc.d -f univention-reload-service remove ||
			:

		echo "Restarting univention-dhcp"
		deb-systemd-invoke restart univention-dhcp || true
		;;

    abort-upgrade|abort-remove|abort-deconfigure)
		;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
		;;
esac

exit 0
