#!/usr/share/ucs-test/runner bash
## desc: In-container integration tests for the ucsschool-bff backends
## exposure: dangerous
## tags: [ucsschool-bff-users]

APP="ucsschool-bff-users"
TEST_DIR="tests/"
CMD="python3 -m pytest -l -v $TEST_DIR"

if ! univention-app shell $APP pytest --help >/dev/null; then
  echo "Installing testing packages..."
  univention-app shell "$APP" python3 -m pip install -U pip wheel
  univention-app shell "$APP" python3 -m pip install poetry
  univention-app shell "$APP" sh -c "poetry export -f requirements.txt --output requirements.txt --dev --without-hashes"
  univention-app shell "$APP" python3 -m pip uninstall --yes poetry
  univention-app shell "$APP" python3 -m pip install -r requirements.txt
fi

echo "Running in container of app '$APP': sh -c \"$CMD\""

univention-app shell "$APP" sh -c "$CMD"
