#!/usr/share/ucs-test/runner bash
## desc: e2e tests of the frontend module agains production setup
## exposure: dangerous
## tags: [ucsschool-bff-users]
## external-junit: /tmp/ui_users_e2e_tests.xml


set -e

HOSTNAME=$(ucr get hostname)
DOMAIN=$(ucr get domainname)

mkdir -p ui_users_e2e_tests/test_results
mkdir -p ui_users_e2e_tests/screenshots

if docker run -ti --rm \
    --env CYPRESS_SIMPLESAML_DOMAIN=ucs-sso."$DOMAIN" \
    --env CYPRESS_KEYCLOAK_DOMAIN=ucs-sso-ng."$DOMAIN" \
    --env CYPRESS_DEFAULT_USER_NAME=admin \
    --env CYPRESS_DEFAULT_USER_PASSWORD=univention \
    --env FRONTEND_DOMAIN="$HOSTNAME"."$DOMAIN" \
    -v "$PWD"/ui_users_e2e_tests/test_results:/e2e-test/test_results \
    -v "$PWD"/ui_users_e2e_tests/screenshots:/e2e-test/cypress/screenshots \
    gitregistry.knut.univention.de/univention/ucsschool-components/ui-users/cypress-tests:branch-juern-e2e-docker; then
    FAILED=0
else
    FAILED=1
fi
cp ui_users_e2e_tests/test_results/e2e-test-results.xml /tmp/ui_users_e2e_tests.xml
exit "$FAILED"
