#!/usr/share/ucs-test/runner bash
## desc: e2e tests of the frontend module agains production setup
## exposure: dangerous
## tags: [ucsschool-bff-users]
## external-junit: /tmp/ui_users_e2e_tests/results/test_e2e_live-combined-report.xml

set -e

HOSTNAME=$(ucr get hostname)
DOMAIN=$(ucr get domainname)

TEST_DIR="$(basename $(readlink -f $(dirname $0)))"
TEST_NAME="$(basename $0)"
RESULT_FOLDER="$HOME/artifacts/$TEST_DIR/$TEST_NAME/cypress"
mkdir -p "$RESULT_FOLDER/results"
mkdir -p "$RESULT_FOLDER/screenshots"

docker run --rm \
    --env CYPRESS_SIMPLESAML_DOMAIN=ucs-sso."$DOMAIN" \
    --env CYPRESS_KEYCLOAK_DOMAIN=ucs-sso-ng."$DOMAIN" \
    --env CYPRESS_DEFAULT_USER_NAME=admin \
    --env CYPRESS_DEFAULT_USER_PASSWORD=univention \
    --env FRONTEND_DOMAIN="$HOSTNAME"."$DOMAIN" \
    --env TEST_PREFIX="97_ucsschool-ram-rankine.04_ui_users_e2e_tests" \
    -v "$RESULT_FOLDER"/results:/e2e-test/cypress/results \
    -v "$RESULT_FOLDER"/screenshots:/e2e-test/cypress/screenshots \
    gitregistry.knut.univention.de/univention/ucsschool-components/ui-users/cypress-tests:latest
