#!/bin/sh

echo "$$" > /tmp/update
sleep 15
if [ "$(cat /tmp/update)" = "$$" ]; then
    . /kelvin/venv/bin/activate
    update_openapi_client --generator java --jar /kelvin/openapi-generator/jar/openapi-generator-cli-*.jar --insecure $DOCKER_HOST_NAME
fi
