usr/share/doc/ucs-school-import                             usr/share/doc/
usr/share/ucs-school-import                                 usr/share/
usr/lib/univention-server/server_password_change.d/gunicorn_ucs-school-import usr/lib/univention-server/server_password_change.d/
modules/univention/admin/hooks.d/*.py                       usr/share/ucs-school-import/hooks.d/
35ucs-school-import.inst                                    usr/lib/univention-install/
