#!/bin/bash
#
# UCS@school HTTP import API
#  prerm file for the debian package
#
# SPDX-FileCopyrightText: 2017-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

case "$1" in
	remove)
	    a2dissite ucs-school-import-http-api.conf
	    deb-systemd-invoke reload apache2

		cp /usr/lib/univention-uninstall/60ucs-school-import-http-api.uinst \
			/usr/lib/univention-install/
	    ;;
	purge)
	    rm -f /var/lib/ucs-school-import-http-api/static/*
esac

exit 0
