#!/bin/sh
#
# UCS@school HTTP import API
#  postinst script for the debian package
#
# SPDX-FileCopyrightText: 2017-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

univention-config-registry set ucsschool/import/generate/import/group?true

#DEBHELPER#

if [ "$1" = "configure" ] && dpkg --compare-versions "$2" lt 16.0.2-12 ; then
	chown -c uas-import:uas-import \
		/etc/ucsschool-import/django_key.secret \
		/etc/ucsschool-import/postgres.secret \
		/etc/ucsschool-import/rabbitmq.secret \
		/var/log/univention/ucs-school-import/ \
		/var/log/univention/ucs-school-import/gunicorn_*.log \
		/var/log/univention/ucs-school-import/http_api.log \
		/var/spool/ucs-school-import/media/uploads/ \
		/var/spool/ucs-school-import/media/uploads/*
	chmod -c o= \
		/etc/ucsschool-import/django_key.secret \
		/etc/ucsschool-import/postgres.secret \
		/etc/ucsschool-import/rabbitmq.secret \
		/var/log/univention/ucs-school-import/ \
		/var/log/univention/ucs-school-import/gunicorn_*.log \
		/var/log/univention/ucs-school-import/http_api.log \
		/var/spool/ucs-school-import/media/uploads/ \
		/var/spool/ucs-school-import/media/uploads/*

	find /var/lib/ucs-school-import/jobs/ -maxdepth 2 -type d -exec chown -c uas-import:uas-import "{}" + -exec chmod -c 0750 "{}" +

	for FILE in ucs-school-import.log ucs-school-import.info new_user_passwords.csv user_import_summary.csv; do
		find /var/lib/ucs-school-import/jobs/ -name "$FILE" -exec chown -c uas-import:uas-import "{}" + -exec chmod -c 0600 "{}" +
	done
fi

systemctl daemon-reload
for SERVICE in postgresql apache2;
do
	echo "Reloading $SERVICE..."
    deb-systemd-invoke reload "$SERVICE.service"
done
for SERVICE in rabbitmq-server ucs-school-import-celery-worker ucs-school-import-http-api;
do
	echo "Restarting $SERVICE..."
    deb-systemd-invoke restart "$SERVICE.service"
done

# conditional restart of univention directory listener
systemctl try-restart univention-directory-listener

if [ "$1" = "configure" ] && dpkg --compare-versions "$2" lt-nl "18.0.14"; then
	eval "$(ucr shell)"
	univention-directory-manager settings/extended_options modify --ignore_not_exists \
		--dn "cn=ucsschoolImportGroup,cn=UCSschool,cn=custom attributes,cn=univention,$ldap_base" \
		--append translationShortDescription='"fr_FR" "Autorisations d’importation dans UCS@school"' \
		--append translationLongDescription='"fr_FR" "Active les options de configuration de ce groupe qui contrôlent les autorisations d’importation dans UCS@school."'

	univention-directory-manager settings/extended_attribute modify --ignore_not_exists \
		--dn "cn=ucsschoolSchool-ImportSchool,cn=UCSschool,cn=custom attributes,cn=univention,$ldap_base" \
		--append translationGroupName='"fr_FR" "Autorisations d’importation"' \
		--append translationShortDescription='"fr_FR" "Écoles autorisées pour l’importation dans UCS@school"' \
		--append translationLongDescription='"fr_FR" "Les membres de ce groupe sont autorisés à importer des comptes d’utilisation dans UCS@school pour les écoles sélectionnées."'

	univention-directory-manager settings/extended_attribute modify --ignore_not_exists \
		--dn "cn=ucsschoolSchool-ImportRole,cn=UCSschool,cn=custom attributes,cn=univention,$ldap_base" \
		--append translationGroupName='"fr_FR" "Autorisations d’importation"' \
		--append translationShortDescription='"fr_FR" "Rôles autorisés pour l’importation dans UCS@school"' \
		--append translationLongDescription='"fr_FR" "Les membres de ce groupe sont autorisés à importer des comptes d’utilisation dans UCS@school pour les rôles sélectionnés."'
fi

exit 0
