#!/bin/sh
#
# UCS@school
#  postinst script for the debian package
#
# SPDX-FileCopyrightText: 2008-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

eval "$(ucr shell server/role)"

if [ "$server_role" = "domaincontroller_master" ] || [ "$server_role" = "domaincontroller_backup" ]; then
	# after 82univention-ucs-school-import-schema.inst
	invoke-rc.d slapd crestart  # FIXME: systemd
fi

exit 0
