usr/share/doc/ucs-school-import                             usr/share/doc/
usr/share/ucs-school-import                                 usr/share/
modules/ucsschool/__init__.py                               usr/share/pyshared/ucsschool/
modules/ucsschool/importer                                  usr/share/pyshared/ucsschool/
modules/univention/admin/hooks.d/*.py                       usr/share/ucs-school-import/hooks.d/
35ucs-school-import.inst                                    usr/lib/univention-install/
