#!/bin/sh
#
# UCS@school
#  preinst script for the debian package
#
# SPDX-FileCopyrightText: 2013-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

# remove old LDAP schema files
# this can be removed after ucsschool-R2
dpkg-maintscript-helper rm_conffile /etc/univention/templates/files/etc/ldap/slapd.conf.d/11univention-ucs-school-import-custom-schema -- "$@"
dpkg-maintscript-helper rm_conffile /etc/ldap/slapd.conf.d/11univention-ucs-school-import-custom-schema -- "$@"

exit 0
