FROM keimlink/sphinx-doc:1.7.1

COPY --chown=1000:1000 requirements.pip /tmp
USER 1000
RUN . .venv/bin/activate && \
    python -m pip install --no-cache-dir --compile -r /tmp/requirements.pip && \
    rm -f /tmp/requirements.pip

EXPOSE 8000

CMD ["sphinx-autobuild", "--host", "0.0.0.0", "--port", "8000", "/home/python/docs", "/home/python/docs/_build/html"]
