#!/usr/bin/make -f
MAIN :=
STYLESHEET := ucsschool
lang := de

COMMON_DIR ?= ../../../../docu/doc-common
include $(COMMON_DIR)/Makefile

OPTIONS += --stringparam front.cover "$(CURDIR)/page-background-title-page.jpg"
