#!/usr/bin/make -f
MAIN := ucsschool-handbuch-4.1r2 ucsschool-lehrer-handbuch-4.1r2 ucsschool-import-handbuch-4.1r2
STYLESHEET := ucsschool
lang := de

COMMON_DIR := ../../../doc-common/docbook
include $(COMMON_DIR)/Makefile

OPTIONS += --stringparam front.cover "$(CURDIR)/page-background-title-page.jpg"
