#!/bin/bash
#
# SPDX-FileCopyrightText: 2016-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

if [ "$1" = "-h" -o "$1" = "--help" ] ; then
	echo "$(basename "$0") [--dry-run]"
	echo
	echo "$(basename "$0") removes unused BDB backing files from"
	echo "/var/lib/ucs-school-webproxy/bdbtemp/."
	exit 1
fi

if [ "$1" = "--dry-run" ] ; then
	find /var/lib/ucs-school-webproxy/bdbtemp/ -name 'BDB*' -type f \( -exec lsof '{}' \; -o -fprintf /dev/stderr 'UNUSED BDB FILE: %p\n' \) > /dev/null
	exit 0
fi
find /var/lib/ucs-school-webproxy/bdbtemp/ -name 'BDB*' -type f \( -exec lsof '{}' \; -o -delete \) > /dev/null
