#!/bin/sh
#
# SPDX-FileCopyrightText: 2015-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

univention-config-registry set \
   'squid/acl/java_updater1/allow/browser/regex=^Java/1\.[56789]\.[0-9]_[0-9][0-9].*$' \
   'squid/acl/java_updater2/allow/browser/string=jupdate' \
   'squid/acl/java_updater3/allow/browser/regex=^Microsoft-CryptoAPI/.*' \
   'squid/acl/java_updater4/allow/browser/string=jucheck' \
   'squid/acl/java_installer1/allow/browser/string=java_installer' \
   'squid/acl/java_installer2/allow/browser/string=JAVACLIENT'

echo >/dev/stderr 'To activate the new configuration a restart of squid is required. e.g.'
echo >/dev/stderr ' invoke-rc.d squid restart'
