#!/bin/sh
#
# Copyright 2015-2016 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

univention-config-registry set \
   'squid/acl/java_updater1/allow/browser/regex=^Java/1\.[56789]\.[0-9]_[0-9][0-9].*$' \
   'squid/acl/java_updater2/allow/browser/string=jupdate' \
   'squid/acl/java_updater3/allow/browser/regex=^Microsoft-CryptoAPI/.*' \
   'squid/acl/java_updater4/allow/browser/string=jucheck' \
   'squid/acl/java_installer1/allow/browser/string=java_installer' \
   'squid/acl/java_installer2/allow/browser/string=JAVACLIENT'

echo >/dev/stderr 'To activate the new configuration a restart of squid is required. e.g.'
echo >/dev/stderr ' invoke-rc.d squid3 restart'
