#!/bin/sh
#
# SPDX-FileCopyrightText: 2015-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

univention-config-registry set \
	'squid/acl/java_applet/allow/browser/regex=^.*Java/1\.[56789]\.[0-9]_[0-9][0-9].*$'

echo >/dev/stderr 'To activate the new configuration a restart of squid is required. e.g.'
echo >/dev/stderr ' invoke-rc.d squid restart'
