# SPDX-FileCopyrightText: 2025-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

# Generated by Django 3.2.19 on 2025-07-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("import_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userimportjob",
            name="user_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("staff", "staff"),
                    ("student", "student"),
                    ("teacher", "teacher"),
                    ("teacher_and_staff", "teacher_and_staff"),
                    ("legal_guardian", "legal_guardian"),
                ],
                max_length=20,
            ),
        ),
    ]
