#!/bin/sh
#
# UCS@school
#  postinst script for the debian package
#
# SPDX-FileCopyrightText: 2017-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

. /usr/share/univention-lib/ucr.sh

univention-config-registry set ucsschool/passwordreset/autosearch?yes

if is_ucr_false ucsschool/passwordreset/autosearch;
    then univention-config-registry set ucsschool/passwordreset/autosearch_on_change?no;
    else univention-config-registry set ucsschool/passwordreset/autosearch_on_change?yes;
fi

exit 0
