#!/usr/share/ucs-test/runner bash
## desc: In-container unit tests
## exposure: safe
## tags: [ucsschool-id-connector]

APP="ucsschool-id-connector"
CMD="cd /$APP/src; /usr/bin/python3 -m pytest -l -v tests/unittests"

echo "Running in container: sh -c \"$CMD\""

univention-app shell "$APP" sh -c "$CMD"
