#!/usr/share/ucs-test/runner bash
## desc: In-container integration tests
## exposure: dangerous
## tags: [ucsschool-id-connector]

APP="ucsschool-id-connector"
CMD1="apk add --no-cache openssh-client sshpass"
CMD2="cd /$APP/src; /usr/bin/python3 -m pytest -m 'not id_broker' -l -v tests/integration_tests"

echo "IP of Traeger 1: $(</var/www/IP_traeger1.txt)"
echo "IP of Traeger 2: $(</var/www/IP_traeger2.txt)"

echo "Running in container: $CMD1"
univention-app shell "$APP" $CMD1

echo "Running in container: sh -c \"$CMD2\""
univention-app shell "$APP" sh -c "$CMD2"
