#!/usr/share/ucs-test/runner bash
## desc: In-container integration tests for ID Broker (Provisioning API) plugin
## exposure: dangerous
## tags: [id-broker]

APP="ucsschool-id-connector"
CMD1="cd /$APP/src;  pytest -lv -m 'id_broker and not id_broker_compatibility' tests/unittests"
CMD2="export UNSAFE_SSL=1 && cd /$APP/src; pytest -lv  -m 'id_broker and not id_broker_compatibility' tests/integration_tests"

echo "IP of ID Broker: $(</var/www/IP_idbroker.txt)"

echo "Running in container: $CMD1"
univention-app shell "$APP" sh -c $CMD1

echo "Running in container: sh -c \"$CMD2\""
univention-app shell "$APP" sh -c "$CMD2"