@startuml
!include _style.iuml

rectangle "HTTP Client" as Client
rectangle "Kelvin REST API" as Kelvin
rectangle "UDM REST API" as UDM
rectangle "OpenLDAP" as LDAP
rectangle "Provisioning-Event-System" as Events
rectangle "Provisioning Consumer" as Consumer
rectangle "SQL-Lesecache" as SQL

Client --> Kelvin : schreiben
Kelvin --> UDM : schreiben
UDM --> LDAP
LDAP --> Events
Events --> Consumer
Consumer --> SQL
Client --> Kelvin : lesen
Kelvin --> SQL : lesen
@enduml
