#!/usr/bin/python2.7
# -*- coding: utf-8 -*-
#
#
# UCS@school Diagnosis Module
#
# Copyright 2020-2021 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.
"""
This module check the constistency of USC@school users, shares and groups
"""
import argparse
import re
import sys

from ldap import INVALID_DN_SYNTAX, NO_SUCH_OBJECT
from ldap.filter import filter_format

from ucsschool.lib.models import School, User
from ucsschool.lib.models.base import WrongObjectType
from ucsschool.lib.roles import (
    create_ucsschool_role_string,
    role_dc_slave_admin,
    role_dc_slave_edu,
    role_exam_user,
    role_memberserver_admin,
    role_memberserver_edu,
    role_school_admin,
    role_school_class,
    role_school_class_share,
    role_staff,
    role_student,
    role_teacher,
    role_workgroup,
    role_workgroup_share,
)
from ucsschool.lib.schoolldap import SchoolSearchBase
from univention.config_registry import ConfigRegistry
from univention.uldap import getAdminConnection


class UserCheck(object):
    def __init__(self):
        ucr = ConfigRegistry()
        ucr.load()
        ldap_base = ucr.get("ldap/base")
        self.lo = getAdminConnection()

        admins_prefix = ucr.get("ucsschool/ldap/default/groupprefix/admins", "admins-")
        teachers_prefix = ucr.get("ucsschool/ldap/default/groupprefix/teachers", "lehrer-")
        staff_prefix = ucr.get("ucsschool/ldap/default/groupprefix/staff", "mitarbeiter-")
        students_prefix = ucr.get("ucsschool/ldap/default/groupprefix/pupils", "schueler-")

        self.teachers_regex = re.compile(
            r"cn={}(?P<ou>[^,]+?),cn=groups,ou=(?P=ou),{}".format(teachers_prefix, ldap_base),
            flags=re.IGNORECASE,
        )
        self.staff_regex = re.compile(
            r"cn={}(?P<ou>[^,]+?),cn=groups,ou=(?P=ou),{}".format(staff_prefix, ldap_base),
            flags=re.IGNORECASE,
        )
        self.students_regex = re.compile(
            r"cn={}(?P<ou>[^,]+?),cn=groups,ou=(?P=ou),{}".format(students_prefix, ldap_base),
            flags=re.IGNORECASE,
        )

        self.ucsschool_obj_classes = {
            "ucsschoolTeacher": role_teacher,
            "ucsschoolStaff": role_staff,
            "ucsschoolStudent": role_student,
            "ucsschoolAdministrator": role_school_admin,
            "ucsschoolExam": role_exam_user,
        }

        self.domain_users_ou = {}
        self.students_ou = {}
        self.teachers_ou = {}
        self.staff_ou = {}
        self.admins_ou = {}

        self.all_schools = [ou.name for ou in School.get_all(self.lo)]
        for ou in self.all_schools:
            self.domain_users_ou[ou] = "cn=Domain Users {0},cn=groups,ou={0},{1}".format(ou, ldap_base)
            self.students_ou[ou] = "cn={0}{1},cn=groups,ou={3},{2}".format(
                students_prefix, ou.lower(), ldap_base, ou
            )
            self.teachers_ou[ou] = "cn={0}{1},cn=groups,ou={3},{2}".format(
                teachers_prefix, ou.lower(), ldap_base, ou
            )
            self.staff_ou[ou] = "cn={0}{1},cn=groups,ou={3},{2}".format(
                staff_prefix, ou.lower(), ldap_base, ou
            )
            self.admins_ou[ou] = "cn={0}{1},cn=ouadmins,cn=groups,{2}".format(
                admins_prefix, ou.lower(), ldap_base
            )

    def check_allowed_membership(self, group_dn, students=False, teachers=False, staff=False):
        """
        This function is used to check if a group of a user matches the users UCS@School role(s).
        The caller specifies the group dn and the user roles which are allowed by setting them to 'True'.
        Example:
        'group_dn' is expected to be a teachers group, i.e. 'teachers' is set to True by the caller.
        If the group turns out to be a students group (where teachers are disallowed) and
        'students' is False, it is an error. A warning will be appended to a list which will be returned.
        """
        errors = []
        if self.students_regex.match(group_dn) and not students:
            errors.append("Disallowed member of students group {}.".format(group_dn))
        if self.teachers_regex.match(group_dn) and not teachers:
            errors.append("Disallowed member of teachers group {}.".format(group_dn))
        if self.staff_regex.match(group_dn) and not staff:
            errors.append("Disallowed member of staff group {}.".format(group_dn))

        return errors

    def get_users_from_ldap(self, school, users):
        ldap_user_list = []
        if users:
            for user_dn in users:
                try:
                    ldap_user_list.append(self.lo.search(base=user_dn)[0])
                except NO_SUCH_OBJECT:
                    print("User with DN {} does not exist.".format(user_dn))
                    sys.exit()
                except INVALID_DN_SYNTAX:
                    print("DN {} has invalid syntax.".format(user_dn))
                    sys.exit()

        if school:
            users_from_school_list = self.lo.search(
                filter=filter_format(
                    "(&(univentionObjectType=users/user)(ucsschoolSchool=%s))", (school,)
                )
            )
            # all users from this school gets added to the list (no duplicates)
            for user in users_from_school_list:
                if user not in ldap_user_list:
                    ldap_user_list.append(user)

        if not users and not school:
            ldap_user_list = self.lo.search(
                filter="(&(univentionObjectType=users/user)(objectClass=ucsschoolType))"
            )

        return ldap_user_list

    def check_user(self, dn, attrs):
        issues = []

        try:
            user_obj = User.from_dn(dn, None, self.lo)
        except WrongObjectType as exc:
            issues.append("Expected a user object, but is not: {}".format(exc))
            return issues

        # check if objectClass is correctly set
        user_obj_classes = attrs.get("objectClass", [])
        if not any(cls in user_obj_classes for cls in self.ucsschool_obj_classes):
            issues.append("User has no UCS@School Object Class set.")

        # check if UCS@school role is correctly set for each school dependent of the objectClass
        user_roles = []

        for cls in user_obj_classes:
            try:
                user_roles.append(self.ucsschool_obj_classes[cls])
            except KeyError:
                continue

        # exam users are an exception. They are objectClass 'ucsschoolStudent',
        # but only require to have the role 'exam_user:school:<userschool>'
        if self.ucsschool_obj_classes["ucsschoolExam"] in user_roles:
            try:
                user_roles.remove(self.ucsschool_obj_classes["ucsschoolStudent"])
            except ValueError:
                pass

        for role in user_roles:
            for school in user_obj.schools:
                ucsschool_role_string = create_ucsschool_role_string(role, school)
                if ucsschool_role_string not in user_obj.ucsschool_roles:
                    issues.append("User does not have UCS@School Role {}".format(ucsschool_role_string))

        # check appropriate group memberships
        users_group_dns = self.lo.searchDn(filter="uniqueMember={}".format(dn))

        # further checks require all of user_obj.schools to exist
        for school in user_obj.schools:
            if school not in self.all_schools:
                issues.append(
                    "User is member of school {}, which does not exist anymore. "
                    "Further tests on this user cannot be performed.".format(school)
                )
                # abort further user checks here
                return issues

        for school in user_obj.schools:
            if self.domain_users_ou[school] not in users_group_dns:
                issues.append("Not member of group {}".format(self.domain_users_ou[school]))
        # check students
        if user_obj.is_student(self.lo):
            for school in user_obj.schools:
                if self.students_ou[school] not in users_group_dns:
                    issues.append("Not member of group {}".format(self.students_ou[school]))
            for group_dn in users_group_dns:
                issues += self.check_allowed_membership(group_dn, students=True)

        # check admins
        if user_obj.is_administrator(self.lo):
            for ou in user_obj.schools:
                if self.admins_ou[ou] not in users_group_dns:
                    issues.append("Not member of group {}".format(self.admins_ou[ou]))
            for group_dn in users_group_dns:
                if self.students_regex.match(group_dn):
                    issues.append("Admin should not be in a students group {}".format(group_dn))

        # check teachers and staff
        if user_obj.is_teacher(self.lo) and user_obj.is_staff(self.lo):
            for ou in user_obj.schools:
                if self.teachers_ou[ou] not in users_group_dns:
                    issues.append("Not member of group {}".format(self.teachers_ou[ou]))
                if self.staff_ou[ou] not in users_group_dns:
                    issues.append("Not member of group {}".format(self.staff_ou[ou]))
            for group_dn in users_group_dns:
                issues += self.check_allowed_membership(group_dn, teachers=True, staff=True)

        # check teachers
        elif user_obj.is_teacher(self.lo):
            for ou in user_obj.schools:
                if self.teachers_ou[ou] not in users_group_dns:
                    issues.append("Not member of group {}".format(self.teachers_ou[ou]))
            for group_dn in users_group_dns:
                issues += self.check_allowed_membership(group_dn, teachers=True)

        # check staff
        elif user_obj.is_staff(self.lo):
            for ou in user_obj.schools:
                if self.staff_ou[ou] not in users_group_dns:
                    issues.append("Not member of group {}".format(self.staff_ou[ou]))
            for group_dn in users_group_dns:
                issues += self.check_allowed_membership(group_dn, staff=True)

        # Check if student is in a class group.
        if not user_obj.school_classes and user_obj.is_student(self.lo):
            issues.append("Is not a member of any school class.")

        # Users should also be member of the corresponding school
        for ou in user_obj.school_classes:
            if ou not in attrs["ucsschoolSchool"]:
                issues.append(
                    "Is member of class {} but school property is not correspondingly set.".format(
                        user_obj.school_classes[ou][0]
                    )
                )

        return issues


def check_groups(school=None):
    ucr = ConfigRegistry()
    ucr.load()
    ldap_base = ucr.get("ldap/base")

    problematic_objects = {}

    lo = getAdminConnection()

    mandatory_global_groups = [
        "cn=DC-Edukativnetz,cn=ucsschool,cn=groups,{}".format(ldap_base),
        "cn=DC-Verwaltungsnetz,cn=ucsschool,cn=groups,{}".format(ldap_base),
        "cn=Member-Edukativnetz,cn=ucsschool,cn=groups,{}".format(ldap_base),
        "cn=Member-Verwaltungsnetz,cn=ucsschool,cn=groups,{}".format(ldap_base),
    ]

    global_groups_issues = []
    for mandatory_global_group in mandatory_global_groups:
        try:
            lo.searchDn(base=mandatory_global_group)
        except NO_SUCH_OBJECT:
            global_groups_issues.append(
                "Mandatory group {} does not exist.".format(mandatory_global_group)
            )

    if global_groups_issues:
        problematic_objects["Global Groups"] = global_groups_issues

    if school:
        all_schools = [school]
    else:
        all_schools = [ou.name for ou in School.get_all(lo)]
    for ou in all_schools:
        search_base = SchoolSearchBase([ou])
        issues = []
        mandatory_groups = [
            "cn=Domain Users {0},cn=groups,ou={0},{1}".format(ou, ldap_base),
            "cn=OU{0}-DC-Edukativnetz,cn=ucsschool,cn=groups,{1}".format(ou, ldap_base),
            "cn=OU{0}-DC-Verwaltungsnetz,cn=ucsschool,cn=groups,{1}".format(ou, ldap_base),
            "cn=OU{0}-Member-Edukativnetz,cn=ucsschool,cn=groups,{1}".format(ou, ldap_base),
            "cn=OU{0}-Member-Verwaltungsnetz,cn=ucsschool,cn=groups,{1}".format(ou, ldap_base),
            "cn=OU{0}-Klassenarbeit,cn=ucsschool,cn=groups,{1}".format(ou, ldap_base),
            "cn=admins-{0},cn=ouadmins,cn=groups,{1}".format(ou, ldap_base),
        ]
        for mandatory_group in mandatory_groups:
            try:
                lo.searchDn(base=mandatory_group)
            except NO_SUCH_OBJECT:
                issues.append("Mandatory group {} does not exist.".format(mandatory_group))

        if issues:
            problematic_objects[search_base.schoolDN] = issues
    return problematic_objects


def check_containers(school=None):
    problematic_objects = {}

    lo = getAdminConnection()

    if school:
        all_schools = [school]
    else:
        all_schools = [ou.name for ou in School.get_all(lo)]

    for ou in all_schools:
        search_base = SchoolSearchBase([ou])
        issues = []
        mandatory_containers = [
            search_base.computers,
            search_base.examUsers,
            search_base.groups,
            search_base.rooms,
            search_base.students,
            search_base.classes,
            search_base.shares,
            search_base.classShares,
            search_base.users,
            search_base.dhcp,
            search_base.networks,
            search_base.policies,
            search_base.printers,
        ]
        for mandatory_container in mandatory_containers:
            try:
                lo.searchDn(base=mandatory_container)
            except NO_SUCH_OBJECT:
                issues.append("Mandatory container {} does not exist.".format(mandatory_container))

        if issues:
            problematic_objects[search_base.schoolDN] = issues
    return problematic_objects


def check_shares(school=None):
    ucr = ConfigRegistry()
    ucr.load()

    problematic_objects = {}

    lo = getAdminConnection()

    if school:
        all_schools = [school]
        school_filter = school
    else:
        all_schools = [ou.name for ou in School.get_all(lo)]
        school_filter = "*"

    if ucr.is_true("ucsschool/import/generate/marktplatz", True):
        for ou in all_schools:
            search_base = SchoolSearchBase([ou])
            marktplatz_share = "cn=Marktplatz,cn=shares,{}".format(search_base.schoolDN)
            try:
                lo.search(base=marktplatz_share)
            except NO_SUCH_OBJECT:
                problematic_objects.setdefault(marktplatz_share, []).append(
                    "The 'Marktplatz' share of school %r does not exist." % (ou,)
                )

    # check if there is a school class for each class share
    classes = []
    role_classes_string = create_ucsschool_role_string(role_school_class, school_filter)
    for dn, attrs in lo.search(filter="(ucsschoolRole={})".format(role_classes_string)):
        classes.append(attrs["cn"])

    role_class_share_string = create_ucsschool_role_string(role_school_class_share, school_filter)
    cls_shares = lo.search(filter="(ucsschoolRole={})".format(role_class_share_string))
    for dn, attrs in cls_shares:
        if attrs["cn"] not in classes:
            problematic_objects.setdefault(dn, []).append(
                "Corresponding class {} is missing.".format(attrs["cn"][0])
            )

    # check if there is a work group for each work group share
    work_groups = []
    role_workgroup_string = create_ucsschool_role_string(role_workgroup, school_filter)
    for dn, attrs in lo.search(filter="(ucsschoolRole={})".format(role_workgroup_string)):
        work_groups.append(attrs["cn"])

    role_workgroup_share_string = create_ucsschool_role_string(role_workgroup_share, school_filter)
    wg_share = lo.search(filter="(ucsschoolRole={})".format(role_workgroup_share_string))
    for dn, attrs in wg_share:
        if attrs["cn"] not in work_groups:
            problematic_objects.setdefault(dn, []).append(
                "Corresponding work group {} is missing.".format(attrs["cn"][0])
            )

    return problematic_objects


def server_in_group_errors(lo, role, members, group_dn):
    problematic_objects = {}
    for dn, attrs in lo.search(filter="(ucsschoolRole={})".format(role)):
        if dn not in members:
            problematic_objects.setdefault(dn, []).append("is not a member of group {}".format(group_dn))
    return problematic_objects


def check_server_group_membership(school=None):
    ucr = ConfigRegistry()
    ucr.load()
    ldap_base = ucr.get("ldap/base")
    problematic_objects = {}

    lo = getAdminConnection()

    if school:
        all_schools = [school]
    else:
        all_schools = [ou.name for ou in School.get_all(lo)]

    dn_dc_edu_global = "cn=DC-Edukativnetz,cn=ucsschool,cn=groups,{}".format(ldap_base)
    dn_dc_admin_global = "cn=DC-Verwaltungsnetz,cn=ucsschool,cn=groups,{}".format(ldap_base)
    dn_member_edu_global = "cn=Member-Edukativnetz,cn=ucsschool,cn=groups,{}".format(ldap_base)
    dn_member_admin_global = "cn=Member-Verwaltungsnetz,cn=ucsschool,cn=groups,{}".format(ldap_base)
    global_groups = [dn_dc_edu_global, dn_dc_admin_global, dn_member_edu_global, dn_member_admin_global]

    members = {}
    for dn in global_groups:
        try:
            members[dn] = lo.search(base=dn)[0][1]["uniqueMember"]
        except KeyError:
            members[dn] = ""
            continue

    for ou in all_schools:
        dn_dc_edu = "cn=OU{0}-DC-Edukativnetz,cn=ucsschool,cn=groups,{1}".format(ou, ldap_base)
        dn_dc_admin = "cn=OU{0}-DC-Verwaltungsnetz,cn=ucsschool,cn=groups,{1}".format(ou, ldap_base)
        dn_member_edu = "cn=OU{0}-Member-Edukativnetz,cn=ucsschool,cn=groups,{1}".format(ou, ldap_base)
        dn_member_admin = "cn=OU{0}-Member-Verwaltungsnetz,cn=ucsschool,cn=groups,{1}".format(
            ou, ldap_base
        )
        role_dc_edu_str = create_ucsschool_role_string(role_dc_slave_edu, ou)
        role_dc_admin_str = create_ucsschool_role_string(role_dc_slave_admin, ou)
        role_member_edu_str = create_ucsschool_role_string(role_memberserver_edu, ou)
        role_member_admin_str = create_ucsschool_role_string(role_memberserver_admin, ou)
        checks = [
            (role_dc_edu_str, dn_dc_edu, dn_dc_edu_global),
            (role_dc_admin_str, dn_dc_admin, dn_dc_admin_global),
            (role_member_edu_str, dn_member_edu, dn_member_edu_global),
            (role_member_admin_str, dn_member_admin, dn_member_admin_global),
        ]

        for role, group_dn, global_group in checks:
            try:
                members[group_dn] = lo.search(base=group_dn)[0][1]["uniqueMember"]
            except KeyError:
                members[group_dn] = ""
            problematic_objects.update(server_in_group_errors(lo, role, members[group_dn], group_dn))
            problematic_objects.update(
                server_in_group_errors(lo, role, members[global_group], global_group)
            )

    return problematic_objects


def print_problematic_objects(objects, entry_string):
    if objects:
        details = "\n\n" + entry_string
        for dn, problems in objects.items():
            details += "\n\n  {}".format(dn)
            for problem in problems:
                details += "\n  - {}".format(problem)
        print(details)


def main():
    parser = argparse.ArgumentParser(
        description="UCS@School Object Consistency Check", formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument(
        "--school",
        help="When specified, only objects of this school get checked.\n"
        "Give the desired school abbreviation.",
    )
    parser.add_argument(
        "--user_dn",
        help="When specified, only the given user(s) gets checked.\n"
        "Give the desired DN(s) of the user(s) seperated by spaces.",
        nargs="+",
    )
    args = parser.parse_args()

    user_dn = school = None
    if args.user_dn:
        user_dn = args.user_dn
    if args.school:
        school = args.school

    user_check = UserCheck()
    users_from_ldap = user_check.get_users_from_ldap(school, user_dn)
    user_problematic_objects = {}
    for dn, attrs in users_from_ldap:
        user_issues = user_check.check_user(dn, attrs)
        if user_issues:
            user_problematic_objects[dn] = user_issues
    group_problematic_objects = check_groups(school)
    container_problematic_objects = check_containers(school)
    share_problematic_objects = check_shares(school)
    server_group_problematic_objects = check_server_group_membership(school)

    print_problematic_objects(user_problematic_objects, "The following USER PROBLEMS were found:")
    print_problematic_objects(group_problematic_objects, "The following GROUP PROBLEMS were found:")
    print_problematic_objects(
        container_problematic_objects, "The following CONTAINER PROBLEMS were found:"
    )
    print_problematic_objects(share_problematic_objects, "The following SHARE PROBLEMS were found:")
    print_problematic_objects(
        server_group_problematic_objects, "The following SERVER GROUP PROBLEMS were found:"
    )


if __name__ == "__main__":
    main()
